### ISSUE TITLE
I'm getting non-consistant behavior which  is making it hard to tell what's going on when I'm trying to debug

### ISSUE THREAD

**Issue by Thermatix** [sparklemotion/nokogiri#1579] opened 2017-01-09 13:53 UTC
ok, so doing : 
```ruby
     puts field
        node =
            (tag[:meta][:before] ? self.send(tag[:meta][:before],item,res) : item)
            .xpath(".%s" % tag[:path])
          puts field == "zoop"
          # puts node.inspect if field == "zoop"
          puts node if field == "zoop"
```

results in 
```
zoop
true
```

but doing:
```ruby
     puts field
      node =
            (tag[:meta][:before] ? self.send(tag[:meta][:before],item,res) : item)
            .xpath(".%s" % tag[:path])
          puts field == "zoop"
          puts node.inspect if field == "zoop"
          puts node if field == "zoop"
```

results in
```
zoop
true
[]
```

Now I definitely know that `item` isn't empty becuase doing a `.inspect`  on the return object inside of the method that I'm doing a `.send` for results in:
```
#<Nokogiri::HTML::Document:0x3ffc5c937194 name="document" children=[#<Nokogiri::XML::DTD:0x3ffc5c936f64...]>
```

I've also had similar issues with doing `.empty?` on `node` not working in the same way

Now obviously `.xpath(".%s" % tag[:path])` is returning nothing (that's an unrelated problem and I know how to fix it) so that's why there's no results but that shouldn't stop `node` from being `[]` regardless of whether I do `puts node.inspect if field == "zoop"` or not

also why is 

```ruby
   puts node.inspect if field == "zoop"
```
not printing output to the terminal?
p.s. I'm going to change that ternary to a `hash.fetch` so don't worry about that.

**Comment by flavorjones** [comment] 2017-01-09 13:59
Hi,

Can you please provide a complete working example so I can reproduce what you're seeing and try to explain it? In your code example it's not clear what the starting values of any of the variables is. Thanks!

**Comment by Thermatix** [comment] 2017-01-09 14:17
when doing 
```ruby
node =    Nokogiri::HTML(body).xpath("some_string")
```

and `node` has no results

you get the weird behavior from above, where you cant get `node`doesn't seem to want to return values, i,e 
```ruby`
puts node 
```

won't print out to the terminal

unless you do somthing like:

```ruby
puts node.inspect
```
in front of it 

like in the examples in the OP where the line was commented out and then it was un-commented out.

**Comment by flavorjones** [comment] 2017-01-13 15:03
Sorry, I'm still not sure what problem you're describing. Are you saying that, given a node contains no text, when you ask it to display its text, it displays nothing? This seems like it's doing the right thing. What behavior would you like to see?

Or, if I'm misunderstanding, you can help me understand more completely by providing a complete working piece of code or a failing test.

**Comment by Thermatix** [comment] 2017-01-16 22:35
Right, so let's say you do an xpath and it returns nothing, I should be able to do:
```ruby
puts node.empty? 
#or
puts node
```

but doing either results in nothing being displayed at all worse is if I'm relying on `node.empty?` to check if there are no results. but it won't work becuase `node.empty?` seems to return nothing just as much as doing `puts node`. 

p.s. I just noticed that the `puts node` isn't printing out `[]`, rather it's the `puts node.inspect`, my mistake, but `puts node` should at least display a blank line (or nil) or something so you can check if the results object is empty.

**Comment by flavorjones** [comment] 2017-02-10 09:20
@Thermatix Thanks for responding.

Unfortunately, I still don't understand what problem you're describing, because you haven't provided a complete working example.

I'm going to close this issue. Please feel free to reach out on the nokogiri-talk mailing list if you'd like further help with Nokogiri. Or, please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.

**Closed by flavorjones** 2017-02-10 09:20 UTC
Labels: needs more info, user help
