### ISSUE TITLE
Nokogiri::XML::XPathContext.register_namespaces fails on UTF-16 file

### ISSUE THREAD

**Issue by aXe1** [sparklemotion/nokogiri#1311] opened 2015-07-05 13:47 UTC
When trying to use any xpath related methods on UTF-16 file this happens:

```
>ruby test.rb
C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/xpath_context.rb:9:in `gsub': incompatible encoding regexp match (US-ASCII regexp with UTF-16 string) (Encoding::CompatibilityError)
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/xpath_context.rb:9:in `block in register_namespaces'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/xpath_context.rb:8:in `each'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/xpath_context.rb:8:in `register_namespaces'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/searchable.rb:158:in `block in xpath'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/searchable.rb:156:in `map'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/searchable.rb:156:in `xpath'
        from C:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri/xml/searchable.rb:186:in `at_xpath'
        from test.rb:6:in `block in <main>'
        from test.rb:4:in `open'
        from test.rb:4:in `<main>'
```

test.rb:

``` ruby
require 'nokogiri'

File.open('test.xml', 'rb') do |file|
  doc = Nokogiri::XML(file)
  p doc.at_xpath('/some/xpath')
end
```

test.xml (encoded in UTF-16LE with BOM):

``` xml
<?xml version='1.0' encoding='UTF-16'?>
<some_tag xmlns='http://some.url.example.com'>
</some_tag>
```

Tested with the same result on two different setups:
Windows box config:

```
>wmic os get Caption, CSDVersion, OSArchitecture /value
Caption=Microsoft Windows 7 Professional
CSDVersion=Service Pack 1
OSArchitecture=64-bit

>ruby -v
ruby 2.0.0p481 (2014-05-08) [i386-mingw32]

>gem list --local | findstr nokogiri
nokogiri (1.6.6.2 x86-mingw32)
```

Linux box config:

```
$ cat /etc/system-release
Fedora release 22 (Twenty Two)

$ uname -a
Linux aXe1-nb 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

$ gem list --local | grep nokogiri
nokogiri (1.6.6.2)
```

**Comment by flavorjones** [comment] 2015-07-05 14:27
Thanks for reporting. This may be a dup of the issue that was brought up in #735, and so perhaps we want to resurrect that PR at this point.

Will take a look. If you could try applying #735 locally and let us know if that addresses your issue, that would be interesting information to know.

**Comment by aXe1** [comment] 2015-07-06 09:16
Retested every XML file in that .xlsx ( #735 ): same error on both platforms for all files.

**Comment by flavorjones** [comment] 2023-01-22 04:05
Can't reproduce. Notes from #735 indicate that this is likely due to an issue with older Rubies and not with Nokogiri. Closing.

**Closed by flavorjones** 2023-01-22 04:05 UTC
Labels: topic/encoding, needs/research
