### ISSUE TITLE
nokogiri escapes "\r" while it shoudln't

### ISSUE THREAD

**Issue by weshatheleopard** [sparklemotion/nokogiri#1356] opened 2015-09-24 20:22 UTC
```
seed_xml = Nokogiri::XML('<?xml version = "1.0" standalone ="yes"?>')
elem = seed_xml.create_element("test", {}, "123\r\n456")
seed_xml << elem
seed_xml.to_xml
 => "<?xml version=\"1.0\" standalone=\"yes\"?>\n<test>123&#xD;\n456</test>\n"
```

`\r` `(#xD)`  should not be escaped, since it is is a valid XML char [as per spec](http://www.w3.org/TR/REC-xml/#NT-Char):

> **2.2 Characters**
> [Definition: A parsed entity contains text, a sequence of characters, which may represent markup or character data.] [Definition: A character is an atomic unit of text as specified by ISO/IEC 10646:2000 [ISO/IEC 10646]. **Legal characters are** tab, **carriage return, line feed**, and the legal characters of Unicode and ISO/IEC 10646. The versions of these standards cited in A.1 Normative References were current at the time this document was prepared. New characters may be added to these standards by amendments or new editions. Consequently, XML processors MUST accept any character in the range specified for Char. ]
> **Character Range**
> `[2]   	Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

Currently, this unwanted escaping [creates troubles](https://github.com/weshatheleopard/rubyXL/issues/202) for me.

**Comment by knu** [comment] 2015-09-25 05:41
Looks like this is caused by xmlEncodeSpecialChars() of libxml2 implemented to escape the carriage return character ([here](https://git.gnome.org/browse/libxml2/tree/entities.c#n838)).  Our JRuby implementation is made to [mimic that](https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/internals/NokogiriHelpers.java#L556-L559).
Apparently libxml2 is doing this intentionally to preserve an input intact (XML is also used as database storage format), but I guess a carriage return right before a newline should be excluded from being escaped.
Would you like to consult the upstream?

**Comment by weshatheleopard** [comment] 2015-09-25 05:50
I will try to do a bit more testing first.

**Comment by flavorjones** [comment] 2016-01-24 07:23
@weshatheleopard Any updates?

**Comment by weshatheleopard** [comment] 2016-01-24 23:54
So after researching, it looks like Microsoft is to blame as usual, and, sadly, for the purposes of making the Excel-compatible files, I MUST have a way to suppress the behavior of  "outputs &#13;\n to avoid the \r from being stripped when the consuming XML parser(s) will find the sequence.", because Excel already accounts for that effect and [expects `\r`s, to be stripped](https://github.com/weshatheleopard/rubyXL/issues/202) (see my last comment in that thread).

Can't we have some kind of "quirks" config flag that could let me suppress the replacement?

**Comment by flavorjones** [comment] 2016-01-26 22:02
@weshatheleopard To restate what @knu said above, this behavior is implemented deep in the libxml2 library, and so we have very little control over it.

Could you apply a post-output `String#gsub` to replace the entity with `\r`?

I don't have any other ideas, and so I'm going to close this for now. If you'd like to continue the conversation or re-open, please comment.

**Closed by flavorjones** 2016-01-26 22:02 UTC
Labels: needs more info

**Comment by neohunter** [comment] 2017-10-16 05:19
I'm having this issue also, I think we should create a flag to `DONT_ESCAPE_CARRIAGE_RETURN` that will `gsub('&#13;', "\r")`

Can I submit a PR?

**Comment by flavorjones** [comment] 2018-02-05 04:50
I'm not inclined to accept a PR like this, simply because it's my belief that Nokogiri should do the bare minimum to make it easy to use the underlying parsing engine. It seems to me that if the parsing engine's output needs to be manipulated, that the user of Nokogiri should do the manipulation.

Could you instead apply a post-output `String#gsub` to replace the entity with `\r`?
