### ISSUE TITLE
&amp; vanishes when XML prefixed with newline

### ISSUE THREAD

**Issue by pluton-house** [sparklemotion/nokogiri#1936] opened 2019-10-24 15:20 UTC
**Describe the bug**

Using `Nokogiri::XML string` when string starts with `\r\n` then text elements lose any &amp; s

**To Reproduce**

Running on Windows:
```ruby
require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node#css" do
    it "should correctly handle &amp;" do
      xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<root>\r\n<name>One&amp;Two</name>\r\n</root>"
      xml2 = "\r\n" + xml1
      
      n1 = Nokogiri::XML(xml1)
      n2 = Nokogiri::XML(xml2)
      
      assert_equal n1.to_xml, n2.to_xml
    end
  end
end
```

**Expected behavior**

XML preceded by newlines should not affect the parsing of the content.

**Environment**

`gem info nokogiri`
```
nokogiri (1.10.4)
    Platform: x64-mingw32
    Authors: Aaron Patterson, Mike Dalessio, Yoko Harada, Tim Elliott,
    Akinori MUSHA, John Shahid, Lars Kanis
    License: MIT
    Installed at: C:/Ruby26-x64/gems

    Nokogiri (?) is an HTML, XML, SAX, and Reader parser

**Comment by flavorjones** [comment] 2020-02-15 13:59
@pluton-house Thanks for asking this question! And thank you for the test that made this easy to reproduce.

One of the things I try to remember to do when I see Nokogiri parsing things in an unexpected way, is to look at the `Document#errors` to see what the underlying parser (libxml2 on CRuby, xerces-j on JRuby) really thinks of the markup.

In your test, if you add:

```
      puts n1.errors.inspect
      puts n2.errors.inspect
```

you'll see that `n1.errors` is empty (`[]`), but `n2.errors` says:

```
[#<Nokogiri::XML::SyntaxError: 2:6: FATAL: XML declaration allowed only at the start of the document>]
```

Normally the parser considers this type of syntax error to be fatal, and would raise an exception; but by default Nokogiri sets the `RECOVER` option which tells the parser to do its best to figure out how to make the document well-formed.

So the result you're seeing is libxml2 going into an error state, trying to recover, and doing the best it can. Unfortunately, the XML spec is silent on the best way to "fix" malformed markup, so although you probably want it to do emit the same document regardless of leading newlines, there's no "right" way.

Because Nokogiri is just a wrapper around the underlying parsing engine, there's no easy way to change this behavior. If you feel strongly about it, you could try sending a bug report upstream to https://gitlab.gnome.org/GNOME/libxml2, but historically these sorts of bugs get closed by the maintainers because the XML spec doesn't address how to do error recovery (and in fact many XML parsers (like `rexml`) don't do error recovery at all).

My advice to you would be to choose either brittle consistency (override the default parsing options so that `RECOVER` isn't used and an exception is raised on syntax errors), or choose robust inconsistency (which is the behavior you're seeing here).

I hope this helps - sorry I couldn't be more useful.

**Closed by flavorjones** 2020-02-15 13:59 UTC

**Comment by pluton-house** [comment] 2020-02-17 10:36
Thanks for that explanation, @flavorjones a useful takeaway for me would be to check errors after parsing the XML, which would at least raise a warning that something 'bad' may have happened. I'll give that a go.
