### ISSUE TITLE
Nokogiri can't find pkg-config on OpenBSD

### ISSUE THREAD

**Issue by frankie-loves-jesus** [sparklemotion/nokogiri#1560] opened 2016-11-29 20:37 UTC
Please see https://github.com/bundler/bundler/issues/5207 -- originally I thought this was a Bundler issue but the guys over there were kind enough to point me in your direction.

That issue should have all the related Nokogiri output required.

**Comment by larskanis** [comment] 2016-11-30 06:55
The pkg-config is not license compatible to nokogiri. It is therefore no fixed dependency of nokogiri since 1.6.8.1. See https://github.com/sparklemotion/nokogiri/issues/1488 

Isn't the error message of bundler and gem install clear enough to either install pkg-config as an additional gem or as a system command?

**Comment by kou** [comment] 2016-11-30 14:23
>The pkg-config is not license compatible to nokogiri.

The pkg-config is license compatible to Nokogiri: https://github.com/sparklemotion/nokogiri/issues/1488#issuecomment-263885087

**Comment by flavorjones** [comment] 2016-11-30 14:45
pkg-config is not a requirement for nokogiri as of 1.6.8.1. please try that version and let us know how you get on.

tagging @larskanis as he's done some work around this recently.

**Comment by frankie-loves-jesus** [comment] 2016-12-03 10:02
@larskanis yes, `gem install pkg-config && gem install nokogiri` works fine. However, `gem install pkg-config && bundle install` does not work unless I explicitly add pkg-config to my Gemfile which feels a bit patchy.

@flavorjones unfortunately that was the version I tried.

**Comment by flavorjones** [comment] 2017-01-28 00:13
@frankie-loves-jesus OK, so I'd like to clarify that `pkg-config` is an overloaded term in this context.

There's [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/) the commandline tool, which is generally used to "find" libraries in a portable manner across a wide number of *nix distros.

Then there's [`pkg-config`](https://rubygems.org/gems/pkg-config/versions/1.1.7) the Ruby gem, which will essentially do the same thing, except in native Ruby.

In order to locate libxml2, libxslt, etc. on your system at installation time, **one of those two needs to be installed.**

The error message you're seeing (which is not referenced in this ticket, but is in https://github.com/bundler/bundler/issues/5207 (an etiquette note for the future is to provide all this information up front when you re-report an issue to a new team; I probably could have cleared this up earlier if you had)), which I found [here](https://gist.github.com/anonymous/a131d987e2ab0f3bff7986c0a2759d9d), indicates that you either:

* have neither `pkg-config` installed,
* **or** don't have libxml2 installed.

Your claim (again, in that other ticket) is that you have `pkg-config`-the-commandline-tool installed. If that's the case, then **we need your help**. This would indicate that `mkmf`'s [`pkg_config`](http://ruby-doc.org/stdlib-1.8.6/libdoc/mkmf/rdoc/Object.html#method-i-pkg_config) method may be broken on your platform (see [this code](https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L115) to understand why I say that).

Alternatively, it could mean that you don't have libxml2 installed on your system. Our [documentation for OpenBSD installation](http://www.nokogiri.org/tutorials/installing_nokogiri.html#openbsd) is pretty thin, and we could sure use your help if this ends up being the issue.

Unfortunately, I don't have access to an OpenBSD system to try to reproduce this issue.

**Can you please help us by:**

1. confirm that you have `pkg-config`-the-commandline-tool installed, by running `which pkg-config`?
2. confirm that you have libxml2 and libxslt development packages installed?
3. confirm that, given the above, you still get this error message?
4. if possible, help us write more complete documentation for OpenBSD?

FWIW, I just tested that the existing code behaves properly on an Ubuntu Linux system, failing when neither the gem nor `pkg-config`-the-commandline-tool are installed; but succeeding if either is installed.

**Comment by vasi** [comment] 2017-01-30 04:39
Anecdotally, I've seeing similar errors, though on a different system. In my case:

* The pkg-config command-line tool exists
* mkmf's `pkg_config()` function calls it to get flags, and then tests that the flags work by compiling/linking
* The compilation succeeds, but returns some `-Wsign-conversion` warnings in ruby.h. I haven't investigated whether or not that's normal, and if not, what the cause is.
* mkmf was given the :werror option, so it considers the warnings an error. It returns nil to `extconf.rb`.
* extconf considers the nil value to indicate that `pkg-config` doesn't exist, and reports `Please install either `pkg-config` or the pkg-config gem`.

I think it would be reasonable to yield a better error message here. Eg: "Unable to determine how to use system libraries. $SOME_USEFUL_ADVICE"

**Comment by flavorjones** [comment] 2017-02-10 09:28
@vasi I just saw this interesting Ruby bug which might be related to your use case:

> https://bugs.ruby-lang.org/issues/13060

@frankie-loves-jesus any thoughts on my comments above? I know it's a lot to unpack, but I do need help understanding what's going on.

**Comment by flavorjones** [comment] 2017-05-10 05:43
@frankie-loves-jesus bump?

**Comment by olleolleolle** [comment] 2017-05-10 20:03
(I got here just now. I'm on an updated OS X system and installed libxml2 again using Homebrew. The homebrew output explained to me that I might need to tell pkg-config where to find its binary:

```shell
export PKG_CONFIG_PATH=/usr/local/opt/libxml2/lib/pkgconfig

**Comment by franklinyu** [comment] 2017-11-26 21:20
@olleolleolle I believe you should be able to install Nokogiri with system libraries (so that you won't need the export path since you are not using Brewed libxml), by

```sh
gem install nokogiri -- --use-system-libraries
```

**Comment by flavorjones** [comment] 2018-02-05 04:25
I'm going to close this, it's been open waiting for the original poster to reply for a while. :cry:

**Closed by flavorjones** 2018-02-05 04:25 UTC
Labels: needs more info

**Comment by Raza403** [comment] 2019-01-25 13:05
This issue is still there, even I have confirmed I have `pkg-config` installed nokogiri gives same error. I have  to add `pkg-config` in Gemfile before nokogiri to make it work.

**Comment by flavorjones** [comment] 2019-01-25 14:05
@Raza403 please open a new issue? Thank you so much!
