### ISSUE TITLE
JRuby-Nokogiri does not generate <?xml>

### ISSUE THREAD

**Issue by ddfreyne** [sparklemotion/nokogiri#1079] opened 2014-04-14 20:12 UTC
The following piece of code generates transformed XML that starts with `<?xml version="1.0" encoding="utf-8"?>` on MRI, but not on JRuby.

### Steps to reproduce

Execute the following on JRuby:

```ruby
input_xml = <<-EOS
<?xml version="1.0" encoding="utf-8"?>
<report>
  <title>My Report</title>
</report>
EOS

input_xsl = <<-EOS
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="utf-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title><xsl:value-of select="report/title"/></title>
      </head>
      <body>
        <h1><xsl:value-of select="report/title"/></h1>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
EOS

require 'nokogiri'

xml = ::Nokogiri::XML(input_xml)
xsl = ::Nokogiri::XSLT(input_xsl)

puts xsl.apply_to(xml)
```

### Expected output

```xml
<?xml version="1.0" encoding="utf-8"?>
<html>
  <head>
    <title>My Report</title>
  </head>
  <body>
    <h1>My Report</h1>
  </body>
</html>
```

This is the output when using Nokogiri on MRI.

### Actual output

```xml
<html><head><title>My Report</title></head><body><h1>My Report</h1></body></html>
```

**Comment by flavorjones** [comment] 2016-02-17 06:00
@jvshahid Thoughts on this?

**Comment by jvshahid** [comment] 2016-02-17 17:58
I can't reproduce this on `master` (or `v1.6.8.rc3`) and jruby `9.0.3.0`. I'll add a test case and close this issue.

**Closed** 2016-02-17 17:59 UTC
Labels: jruby

**Comment by jvshahid** [comment] 2016-02-17 23:28
Just noticed that the JRuby implementation always include the xml declaration, even when it shouldn't. See https://github.com/sparklemotion/nokogiri/issues/1430 for more info
