### ISSUE TITLE
Segmentation fault from node.replace when using libxml-ruby and nokogiri

### ISSUE THREAD

**Issue by gazay** [sparklemotion/nokogiri#1270] opened 2015-03-25 15:10 UTC
I start having this problem in my production application and reduced it to the following script: https://gist.github.com/gazay/6275c98062127ac5b947

It reproduced in any linux environment (on mac os x I can't reproduce this fault). I've tried this script on ruby 2.1.5/2.2.0/2.2.1/trunk. Also I've tried it on nokogiri 1.6.5/1.6.6.2 and libxml-ruby 2.7.0/2.8.0.

**Comment by flavorjones** [comment] 2015-09-30 12:34
Hi @gazay,

Sorry for not responding earlier. What stands out to me is:

```
require 'libxml'
```

Why are you using both libxml-ruby and nokogiri?

Nokogiri tries very hard to work around how libxml-ruby manages libxml2 memory, but officially it's just not something I'm interested in spending time supporting.

That said, I'll take a look and see if this is something we can easily work around (but I doubt it).

**Comment by gazay** [comment] 2015-09-30 12:46
Hello! I don't remember it already =) But I think in our production application it was in dependencies for a couple of gems. After we had found this – we left only nokogiri in our gemfile. I think it would be enough to point this somewhere in readme, that if someone will experience this error – they can find it quickly

**Comment by flavorjones** [comment] 2016-02-17 02:46
I'm going to consider this a duplicate of #1426. Please follow along there?

**Closed by flavorjones** 2016-02-17 02:46 UTC
Labels: libxml-ruby gem conflicts
