### ISSUE TITLE
RelaxNG Validation in JRuby Version

### ISSUE THREAD

**Issue by inukshuk** [sparklemotion/nokogiri#727] opened 2012-07-12 11:55 UTC
Is RelaxNG validation currently supported by the JRuby version? I assume it is, because I noted that jing.jar is packaged with nokogiri, however, I cannot load a schema:

    > schema = Nokogiri::XML::RelaxNG(File.open('vendor/schema/csl.rng'))
    Java::JavaLang::NoSuchMethodError: com.thaiopensource.relaxng.parse.sax.SAXParseable.<init>(Lcom/thaiopensource/xml/sax/XMLReaderCreator;Lorg/xml/sax/InputSource;Lorg/xml/sax/ErrorHandler;)V
    	from com.thaiopensource.relaxng.jarv.VerifierFactoryImpl.compileSchema(Unknown Source)
    	from org.iso_relax.verifier.VerifierFactory.compileSchema(VerifierFactory.java:157)
    	from org.iso_relax.verifier.VerifierFactory.compileSchema(VerifierFactory.java:139)
    	from nokogiri.XmlRelaxng.getSchema(XmlRelaxng.java:123)
    	from nokogiri.XmlRelaxng.createSchemaInstance(XmlRelaxng.java:87)
    	from nokogiri.XmlSchema.getSchema(XmlSchema.java:151)
    	from nokogiri.XmlSchema.from_document(XmlSchema.java:143)
    	from nokogiri.XmlSchema$s$1$0$from_document.call(XmlSchema$s$1$0$from_document.gen:65535)
    	from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
    	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
    	from org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
    	from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
    	from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    	from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
    	from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:199)
       	from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
    ... 141 levels...
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    	from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
    	from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:199)
    	from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
    	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
    	from Users.sylvester.$_dot_rvm.rubies.jruby_minus_1_dot_6_dot_7_dot_2.bin.irb.__file__(/Users/sylvester/.rvm/rubies/jruby-1.6.7.2/bin/irb:17)
    	from Users.sylvester.$_dot_rvm.rubies.jruby_minus_1_dot_6_dot_7_dot_2.bin.irb.load(/Users/sylvester/.rvm/rubies/jruby-1.6.7.2/bin/irb)
    	from org.jruby.Ruby.runScript(Ruby.java:697)
    	from org.jruby.Ruby.runScript(Ruby.java:690)
    	from org.jruby.Ruby.runNormally(Ruby.java:597)
    	from org.jruby.Ruby.runFromMain(Ruby.java:446)
    	from org.jruby.Main.doRunFromMain(Main.java:369)
    	from org.jruby.Main.internalRun(Main.java:258)
    	from org.jruby.Main.run(Main.java:224)
    	from org.jruby.Main.run(Main.java:208)
    	from org.jruby.Main.main(Main.java:188)

This works on MRI. And I can load the same schema directly with jing. I'm willing to take a stab at fixing this, but wanted to ask if I'm doing something obviously wrong there and/or get pointers how to tackle this.

Thanks for nokogiri!

**Comment by flavorjones** [comment] 2016-02-17 05:11
Lots to unpack here, but I'm going to close this for now because it's so old.

The file/string wart you mentioned was fixed, I believe, in 1.6.7.

If you feel this is still a problem, let's open a new issue for it so we can generate some good reproducible test cases to demonstrate what's going on. Thanks.

**Closed by flavorjones** 2016-02-17 05:11 UTC
Labels: jruby
