### ISSUE TITLE
JRuby cache clearing issue since 1.6.2 affects Blather (Adhearsion)

### ISSUE THREAD

**Issue by chewi** [sparklemotion/nokogiri#1708] opened 2018-01-02 14:41 UTC
The [Blather](https://github.com/adhearsion/blather) project, an important part of [Adhearsion](https://github.com/adhearsion/adhearsion), has been [severely affected](https://github.com/adhearsion/blather/issues/145) by a cache clearing issue in the JRuby implementation since 1.6.2, and as such has had to lock the Nokogiri version back to 1.6.1. This is obviously a security concern and we are missing out on other fixes made since.

Blather (indirectly) subclasses `Nokogiri::XML::Node` as `Blather::XMPPNode`. It's hard to explain exactly what happens as I'm not the author and it's not the simplest of libraries but somewhere along the line, `node.parent` is called and rather than returning the original `Blather::XMPPNode` instance that was created earlier, a new `Nokogiri::XML::Element` instance is returned instead. It may not matter that the instance is different but the change in class certainly does matter. It should go without saying that this does not happen under MRI.

I bisected the problem back to sparklemotion/nokogiri@e51bb1d, made by @mbklein. I obviously had to raise an eyebrow when I saw that the following comment had since been added above the first clearCachedNote statement by @jvshahid.

```java
// TODO: this feels kind of weird, why are we clearing the XmlNode
// cache here !!!
clearCachedNode(node);
```

Indeed, if I comment out this line, the problem goes away and all the Nokogiri tests still pass. Unhelpfully, if I comment out the other clearCachedNode line below, all the Nokogiri tests still pass, so perhaps there is insufficient testing here.

My limited understanding tells me that because the cache is being cleared, the original Ruby instance is lost and a new one is being created in `NokogiriHelpers#constructNode` with the hardcoded class of `Nokogiri::XML::Element`. Given that we only have the `org.w3c.dom.Node` instance to recreate from, Ruby-specific details such as which subclass was used originally, are lost.

It is not clear to me exactly when the cache is supposed to be cleared. If it can happen quite easily then perhaps the approach that Blather takes is no longer viable. However, given the interesting comment noted above, I suspect it is currently being cleared more than it should.

**Comment by jvshahid** [comment] 2018-01-05 04:49
It looks like the `clearCachedNode` came from this pr https://github.com/sparklemotion/nokogiri/pull/1054 which was trying to address #1034. I verified that [this is the only change](https://github.com/sparklemotion/nokogiri/blob/734d4d4763c1dee9601d7c385990e237a5eee8a9/ext/java/nokogiri/XmlNode.java#L505-L507) required to make the test pass. This has been the case since the pr was merged in, not a side effect of another change that has been made since then. may be @mbklein could remember why it was necessary to call `clearCachedNode`

**Comment by mbklein** [comment] 2018-01-10 17:00
Clearing cached nodes was necessary under certain circumstances because the cached instance of the node was bound to the wrong namespace. I believe I also added tests to guard against regression, so if the tests still pass without the `clearCachedNode` call, I won't argue for keeping it.

That said, I haven't done any work on nokogiri's Java internals since late 2014, so basing anything on my current memory and knowledge is exactly as risky as you might think. 😄

**Comment by chewi** [comment] 2018-01-10 17:06
Thanks for letting us know. I can go back to that commit and check whether removing that line breaks your test when I get a minute.

**Comment by jvshahid** [comment] 2018-01-10 17:38
I definitely checked and it doesn't break any tests. Given my initial
confusion (hence the TODO in the code) and the fact that it doesn't
cause any tests to break atm. I am inclined to get rid of that line.

**Comment by chewi** [comment] 2018-01-15 11:11
I can confirm that going back to sparklemotion/nokogiri@e51bb1d1e7f271174244925cf8f431823979a74d and removing both `clearCachedNode` calls has no effects on the test. I also tried sparklemotion/nokogiri@b6a34d936fa29aa26f1b4ea39c5ac73367744f0e, which is the last change involving @mbklein. Only removing the `nsUri = null` line makes any difference. I suggest we remove the first `clearCachedNode` call. It seems out of place and I wonder if it was a test that was left in by accident. The second `clearCachedNode` call does at least look like it has a purpose.

**Comment by flavorjones** [comment] 2018-01-29 06:02
I'm not sure I understand what's being suggested for next steps. I'd be happy to merge a PR ...

**Comment by jvshahid** [comment] 2018-01-29 15:41
Opened a pr https://github.com/sparklemotion/nokogiri/pull/1716 with the proposed changes

**Comment by chewi** [comment] 2018-01-29 15:53
Hmm, I already opened #1715. I only removed the first call though so you'll need to decide which one to go with.

**Comment by jvshahid** [comment] 2018-01-29 18:06
I think it is fine to get rid of both calls since neither one affect the tests

**Comment by chewi** [comment] 2018-01-29 18:09
Okay, closed mine.

**Closed** 2018-02-19 06:18 UTC
Labels: jruby
