### ISSUE TITLE
Combo pseudo-selectors not working

### ISSUE THREAD

**Issue by amaisano** [sparklemotion/nokogiri#1022] opened 2013-12-17 19:42 UTC
The following combos are being ignored - the styles aren't being applied.

ul > li:not(.expanded):last-child

ul li:not(:first-child).current

ul li:not(.expanded):not(:last-child).current

These are pretty crazy selectors I know, but are vital to the nested menu system we are using in HTML. When the :not() and the :last-child selectors are used on their own, they work fine with nokogiri, but when combined with other pseudo selectors and chained classes, they don't seem to work.

**Comment by flavorjones** [comment] 2021-11-23 23:00
Hi, and apologies for not responding for such a long time.

Unfortunately,I'm unable to reproduce what you're describing in Nokogiri v1.12. Here's the script I'm using to try to reproduce:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

html = <<~HTML
  <html>
    <body>
      <ul>
        <li class="early">first</li>
        <li class="middle">second</li>
        <li class="late">third</li>
      </ul>
    </body>
  </html>
HTML

doc = Nokogiri::HTML5(html)

def find_css(doc, query)
  puts "looking for '#{query}' ..."
  puts doc.css(query)
  puts
end

find_css(doc, "ul li:first-child")
find_css(doc, "ul li:first-child.early")
find_css(doc, "ul li:not(:first-child)")
find_css(doc, "ul li:not(:first-child).middle")
find_css(doc, "ul li:not(:first-child):not(.middle)")
find_css(doc, "ul li:not(:first-child).late")
```

and here's the output from that script:

```
$ ./1022-css-pseudo-selectors.rb 
looking for 'ul li:first-child' ...
<li class="early">first</li>

looking for 'ul li:first-child.early' ...
<li class="early">first</li>

looking for 'ul li:not(:first-child)' ...
<li class="middle">second</li>
<li class="late">third</li>

looking for 'ul li:not(:first-child).middle' ...
<li class="middle">second</li>

looking for 'ul li:not(:first-child):not(.middle)' ...
<li class="late">third</li>

looking for 'ul li:not(:first-child).late' ...
<li class="late">third</li>
```

I realize it's been quite a long time since you opened this issue, so I'm going to close it. But if you can help me understand and reproduce what you saw, I would be happy to reopen this issue and fix it.

**Closed by flavorjones** 2021-11-23 23:00 UTC
Labels: topic/css
