### ISSUE TITLE
Memory leak!! When I create xml of 5MB, it is consuming 80MB of memory. And WON'T be released.

### ISSUE THREAD

**Issue by BlackNightFury** [sparklemotion/nokogiri#1727] opened 2018-02-23 21:19 UTC
I am running production on CentOS 7 which is using Nokogiri to build and parse XML.

But when I create XML of 5MB, it is consuming 80MB of memory and memory won't be released.
So after 1 or 2 days, servers are being crashed and down.

I need your help URGENTLY if you have any experience on it.

Thanks

**Comment by tenderlove** [comment] 2018-02-24 21:53
Hi @BlackNightFury.  We need more information to help you. Can you give us a script that will reproduce the problem?  Thanks.

**Comment by flavorjones** [comment] 2018-02-25 19:33
@BlackNightFury Please answer the questions from the issue template that you deleted:

```
**What problems are you experiencing?**

**What's the output from `nokogiri -v`?**

**Can you provide a self-contained script that reproduces what you're seeing?**
```

**Comment by BlackNightFury** [comment] 2018-02-25 21:42
Hi, @flavorjones and @flavorjones . Thanks for your time in advance.

1) What problems are you experiencing?
We have one production server and it is working with XML mostly. We generate XML from Hash array and also parse XML string into XML document using Nokogiri.

What I am facing with, is that nokogiri is eating 80MB of Ram to generate 5MB and memory won't be release. So our server needs to restart often.

2) I am using nokogiri version 1.7.2

3) Script
    bundle = Nokogiri::XML::Builder.new do |xml|
      xml.comment(Comment.")
      xml.Bundle(:xmlns => "http://url") {
        xml.comment("Start of header elements")
        xml.id(:value => UUID.new.generate)
        xml.meta {
          xml.lastUpdated(:value => Time.now.iso8601)
        }
        xml.type(:value => "searchset")
        if(count != 0 && count < orgs.count)
          xml.total(:value => count)
        else
          xml.total(:value => orgs.count)
        end

        xml.link {
          xml.relation(:value => "self")
          if(format == "xml")
            xml.url(:value => "_format=xml")
          elsif(format == "json")
            xml.url(:value => "_format=json")
          else
            $logger.warn("unknown format #{format}")
          end
        }
        
        i = 0

        orgs.each { |org|
          #  halt loop if count var was specified
          if(i >= count)
            $logger.warn("Enforcing server limit parm of #{count} entries max instead of returning up to #{orgs.size}")
            break
          end

          if(orgs[i].nil? == true)
            puts "Reached end of orgs list"
            break
          end

          xml.comment("The entry object is repeated for each organization listed in the directory")
          xml.entry {
            xml.fullUrl(:value => "#{i}")
            xml.resource {
              xml.Organization(:xmlns => "url") {
                xml.name(:value => orgs[i]['field1'])
        
                xml.comment('Comment')
                if(orgs[i]['field2'].nil? == false)
                  xml.address {
                      xml.position{
                        xml.city(:value => orgs[i]['field4']) if(orgs[i]['field4'].nil? == false)
                        xml.state(:value => orgs[i]['field5']) if(orgs[i][field5'].nil? == false)
                        xml.longitude(:value => orgs[i]['field6'])
                        xml.latitude(:value => orgs[i]['field7'])
                        if(orgs[i]['field8'].nil? == false)
                          xml.altitude(:value => orgs[i]['field8']) 
                        end
                      }
                  }
                end
              }
            }
          }
        # Louis I moved this here to fix a bug I made
        i = i + 1
        }
      }
    end
  
    $logger.warn "Returning XML document"
    str = bundle.to_xml
   

orgs Array contains more than 8000 elements.

Looking for your response

**Comment by flavorjones** [comment] 2018-02-25 21:52
I'd like to point out that the code you pasted above contains several syntax errors. I'll fix them and continue, but I'd like you to make sure you pasted working code.

**Comment by BlackNightFury** [comment] 2018-02-25 22:00
Actually, I copied the part of my server code because it contains confidential informations. Maybe I made error and sorry about that. If you can fix it and test, then it will be really great for me.

**Comment by flavorjones** [comment] 2018-02-25 22:20
@BlackNightFury Here's the script I'm running (based on the one you pasted above):

```
#!/usr/bin/env ruby

require 'nokogiri'
require 'uuid'
require 'time'

orgs = []

8000.times do |j|
  orgs[orgs.length] = {
    'field1' => "asdf1#{j}"*100,
    'field2' => "asdf2#{j}"*100,
    'field3' => "asdf3#{j}"*100,
    'field4' => "asdf4#{j}"*100,
    'field5' => "asdf5#{j}"*100,
    'field6' => "asdf6#{j}"*100,
    'field7' => "asdf7#{j}"*100,
    'field8' => "asdf8#{j}"*100,
  }
end

j = 0
loop do
  j += 1
  bundle = Nokogiri::XML::Builder.new do |xml|
    xml.comment("Comment.")
    xml.Bundle(:xmlns => "http://url") {
      xml.comment("Start of header elements")
      xml.id(:value => UUID.new.generate)
      xml.meta {
        xml.lastUpdated(:value => Time.now.iso8601)
      }
      xml.type(:value => "searchset")
      xml.total(:value => orgs.count)

      xml.link {
        xml.url(:value => "_format=xml")
      }
      
      orgs.each_with_index { |org, i|
        xml.comment("The entry object is repeated for each organization listed in the directory")
        xml.entry {
          xml.fullUrl(:value => "#{i}")
          xml.resource {
            xml.Organization(:xmlns => "url") {
              xml.name(:value => org['field1'])
              
              xml.comment('Comment')
              xml.address {
                xml.position{
                  xml.city(:value => org['field4'])
                  xml.state(:value => org['field5'])
                  xml.longitude(:value => org['field6'])
                  xml.latitude(:value => org['field7'])
                  xml.altitude(:value => org['field8']) 
                }
              }
            }
          }
        }
      }
    }
  end

  if j == 1
    length = bundle.to_xml.length
    puts "doc length is #{length} bytes"
  end

  if j % 10 == 0
    pid, size = `ps ax -o pid,rss | grep -E "^[[:space:]]*#{$$}"`.strip.split.map(&:to_i)
    puts "after #{j} iterations: process memory: #{size}"
  end
end
```

and here's the output so far:

```
nokogiri $ ~/foo.rb
doc length is 46581227 bytes
after 10 iterations: process memory: 445812
after 20 iterations: process memory: 535488
after 30 iterations: process memory: 536320
after 40 iterations: process memory: 548728
after 50 iterations: process memory: 701584
after 60 iterations: process memory: 702376
after 70 iterations: process memory: 702640
after 80 iterations: process memory: 702640
after 90 iterations: process memory: 702904
after 100 iterations: process memory: 703432
after 110 iterations: process memory: 703432
after 120 iterations: process memory: 703432
after 130 iterations: process memory: 703432
after 140 iterations: process memory: 703432
after 150 iterations: process memory: 703432
after 160 iterations: process memory: 703432
after 170 iterations: process memory: 703432
after 180 iterations: process memory: 703432
after 190 iterations: process memory: 703432
after 200 iterations: process memory: 703432
after 210 iterations: process memory: 703696
after 220 iterations: process memory: 703696
```

indicating that memory usage is pretty stable. Note that this document size is ~46MB, which is quite large. I'm going to let it run for a bit to see if I see a slow increase in memory usage.

**Comment by BlackNightFury** [comment] 2018-02-25 22:25
Let's imagine that one endpoint in sinatra app returns that xml string, can you confirm that if the used memory is released after that endpoint?

Thanks

**Comment by flavorjones** [comment] 2018-02-25 22:29
@BlackNightFury can you please provide the output from `nokogiri -v` as requested?

**Comment by BlackNightFury** [comment] 2018-02-25 22:30
Here is the output of nokogiri -v

Nokogiri (1.8.1)
    ---
    warnings: []
    nokogiri: 1.8.1
    ruby:
      version: 2.2.6
      platform: x64-mingw32
      description: ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxml2/2.9.5"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxslt/1.1.30"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.5
      loaded: 2.9.5

**Comment by flavorjones** [comment] 2018-02-25 22:31
@BlackNightFury this is at odds with what you said above, which was that you're running Nokogiri 1.7.2. Can you please help me understand this difference?

**Comment by BlackNightFury** [comment] 2018-02-25 22:32
Sorry, that was my mistake. I used 1.7.2 but tried changing version to see if it works.

**Comment by flavorjones** [comment] 2018-02-25 22:33
The output from running my script is:

```
$ ~/foo.rb
doc length is 46581227 bytes
after 10 iterations: process memory: 445812
after 20 iterations: process memory: 535488
after 30 iterations: process memory: 536320
after 40 iterations: process memory: 548728
after 50 iterations: process memory: 701584
after 60 iterations: process memory: 702376
after 70 iterations: process memory: 702640
after 80 iterations: process memory: 702640
after 90 iterations: process memory: 702904
after 100 iterations: process memory: 703432
after 110 iterations: process memory: 703432
after 120 iterations: process memory: 703432
after 130 iterations: process memory: 703432
after 140 iterations: process memory: 703432
after 150 iterations: process memory: 703432
after 160 iterations: process memory: 703432
after 170 iterations: process memory: 703432
after 180 iterations: process memory: 703432
after 190 iterations: process memory: 703432
after 200 iterations: process memory: 703432
after 210 iterations: process memory: 703696
after 220 iterations: process memory: 703696
after 230 iterations: process memory: 703696
after 240 iterations: process memory: 703696
after 250 iterations: process memory: 703696
after 260 iterations: process memory: 703960
after 270 iterations: process memory: 703960
after 280 iterations: process memory: 862624
after 290 iterations: process memory: 862888
after 300 iterations: process memory: 862888
after 310 iterations: process memory: 862888
after 320 iterations: process memory: 904864
after 330 iterations: process memory: 904864
... <snip> ...
after 650 iterations: process memory: 904864
after 660 iterations: process memory: 904864
after 670 iterations: process memory: 904864
after 680 iterations: process memory: 904864
after 690 iterations: process memory: 904864
after 700 iterations: process memory: 904864
after 710 iterations: process memory: 904864
after 720 iterations: process memory: 904864
after 730 iterations: process memory: 904864
after 740 iterations: process memory: 904864
after 750 iterations: process memory: 904864
```

which indicates to me that Nokogiri 1.8.2 using vendored libxml 2.9.7 is not leaking memory.

I'd like to ask that you run this script and tell me if you get different results. If you do get different results, then we need to dig into the differences between your installation and mine. If you do not get different results, then I need to ask you to provide a reproducible test case that demonstrates what you're seeing outside the context of your web server and web application framework.

**Comment by BlackNightFury** [comment] 2018-02-25 22:44
I have one question here. When will that memory be release?

Just Imagine that that content is the part of one function and that function returns bundle.to_xml.
After calling of that function, memory used for bundle will be released?

**Comment by flavorjones** [comment] 2018-02-25 22:46
If you have general questions about Ruby's garbage collection, you may want to ask on a general list like ruby-talk.

That said, I can summarize briefly that Ruby uses a mark-and-sweep GC mechanism, meaning that when GC kicks in, it looks for Ruby objects that are no longer referenced and cleans them. More generally, though, process size isn't directly related to memory usage because of memory fragmentation, which is particularly problematic when generating lots of small strings (as you appear to be).

**Comment by flavorjones** [comment] 2018-02-25 22:46
Note also that you may need to adjust the line of the script that finds the process's resident memory size, as it assumes Linux, and I can see you're on Windows.

**Comment by BlackNightFury** [comment] 2018-02-25 22:49
I am already running script on linux box.

Then why is the usage of memory of my server only increasing after calling that endpoint?

I can understand the usage of memory can be increased while processing request. But after respond, I think usage of memory should be decreased. Right?

**Comment by flavorjones** [comment] 2018-02-25 22:53
I'm super duper confused by your questions right now. Are you running on windows in product, or on linux? Are you running 1.7.2 in production, or 1.8.1?

You'll get much higher quality answers if you help us understand what you're doing more precisely.

I can't help you diagnose memory leaks in your web app or web framework. I can only help diagnose them if they're in Nokogiri and if we can reproduce them.

**Comment by BlackNightFury** [comment] 2018-02-25 22:54
Yes, I am using 1.81 on linux for production server.

And if I remove that nokogiri part, then usage of memory isn't being increased. That is why I am asking your help.

So please help me.

**Comment by flavorjones** [comment] 2018-02-25 22:58
To be clear, Nokogiri is going to use a lot of memory to generate this document; and the strings themselves that make up the document will take up more memory. Not 100% of that memory will be completely reclaimed, due to memory fragmentation (as I mentioned above). This is why I let the script I adapted from your example run for nearly 1000 responses, and you can see that the process is taking ~800MB of memory to generate a ~46MB document; but that eventually it stabilizes at that point.

You may be seeing large amounts of memory being used; this does not necessarily mean it's a leak. In order to determine if the memory is truly "lost", meaning it's a proper leak, it's critical that we be able to reproduce the effect in a self-contained script, given a specific version of nokogiri and libxml2.

Unless you can help me reproduce what you're seeing, we're not going to get much further than we have so far.

**Comment by BlackNightFury** [comment] 2018-02-25 23:02
I can understand that usage of memory can be increased when generate or parse xml using nokogiri.

So here is what I am understandings:
You are saying that memory usage will be increased but that increase will be stopped at one point.

Right?

**Comment by flavorjones** [comment] 2018-02-27 14:01
I accidentally left my repro script running all day yesterday:

```
after 22640 iterations: process memory: 696 kB / 712 kB
after 22650 iterations: process memory: 752 kB / 740 kB
after 22660 iterations: process memory: 740 kB / 760 kB
after 22670 iterations: process memory: 756 kB / 844 kB
after 22680 iterations: process memory: 844 kB / 748 kB
after 22690 iterations: process memory: 716 kB / 740 kB
after 22700 iterations: process memory: 752 kB / 788 kB
after 22710 iterations: process memory: 704 kB / 700 kB
after 22720 iterations: process memory: 760 kB / 796 kB
after 22730 iterations: process memory: 700 kB / 788 kB
after 22740 iterations: process memory: 796 kB / 708 kB
after 22750 iterations: process memory: 700 kB / 748 kB
after 22760 iterations: process memory: 716 kB / 800 kB
after 22770 iterations: process memory: 852 kB / 716 kB
```

so there's no memory leak here. I'm going to close this, and I encourage you to engage with people on ruby-talk (or other general forum) about how memory management works in the Ruby interpreter.

Thanks for using Nokogiri, and I'm sorry I wasn't of more help.

**Closed by flavorjones** 2018-02-27 14:01 UTC
Labels: needs more info
