### ISSUE TITLE
Rails 4.2 installation issues with Nokogiri on OS X

### ISSUE THREAD

**Issue by androbtech** [sparklemotion/nokogiri#1214] opened 2014-12-23 00:26 UTC
Some developers have had issues when installing Nokogiri because it depends on libiconv, which doesn't ship with OS X Yosemite. I do know we have /usr/lib/libiconv.dylib, but I can't find header files.

I faced issues before Rails 4.2 release while trying to install nokogiri.

We at Tokaido would like to make developer's life easier by simply shipping with a static build of libiconv included with a Ruby build that has a patched rbconfig.rb file. With this hack, when someone tries to install nokogiri on our isolated environment, it will implicitly add the configure flags to the path where our own libiconv header and libs are.

This approach works. The problem is that this [line](https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L453) is the showstopper, no matter the flags we pass in.

```
if darwin_p && !File.exist?('/usr/include/iconv.h')
```

I'm somewhat worried about the rest of rubyists trying to install latest Rails and face this. Tokaido will ship with Rails 4.2 and nokogiri already compiled so it shouldn't be a problem for them but I wanted to share this.

With our isolated environment and assuming we have 'iconv.h' at /path/to/tokaido/iconv/include/iconv.h (which we do), if we do a symlink from /usr/include/iconv.h (using sudo) to our Tokaido iconv.h and run:

```gem install nokogiri --no-ri --no-rdoc```

it compiles successfully.

**Comment by flavorjones** [comment] 2015-10-29 03:33
I believe this will be fixed by the fix proposed in #1218.

**Comment by mojca** [comment] 2015-10-29 09:54
I tried the patch from http://buegling.com/blog/2015/4/26/building-nokogiri-on-os-x, but I still get the same problem:

```
Activating libxslt 1.1.28 (from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28)...
checking for main() in -llzma... no
checking for xmlParseDoc() in libxml/parser.h... no
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
-----
libxml2 is missing.  Please locate mkmf.log to investigate how it is failing.
-----
*** extconf.rb failed ***
```

with mkmf.log complaining about libiconv:

```
have_func: checking for xmlParseDoc() in libxml/parser.h... -------------------- no

"clang -o conftest -I/Users/me/.rbenv/versions/2.2.3/include/ruby-2.2.0/x86_64-darwin11.0 -I/Users/me/.rbenv/versions/2.2.3/include/ruby-2.2.0/ruby/backward -I/Users/me/.    rbenv/versions/2.2.3/include/ruby-2.2.0 -I. -I/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/        include -I/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/include/libxml2 -I/Users/me/.rbenv/       versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/include/libxml2 -I/Users/me/.rbenv/versions/2.2.3/include  -            D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   "-DNOKOGIRI_LIBXML2_PATH=\"/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.  rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2\"" "-DNOKOGIRI_LIBXML2_PATCHES=\"\"" "-DNOKOGIRI_LIBXSLT_PATH=\"/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/      nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28\"" "-DNOKOGIRI_LIBXSLT_PATCHES=\"\""  -O3 -Wno-error=shorten-64-to-32  -pipe  -DNOKOGIRI_USE_PACKAGED_LIBRARIES   conftest.c  -L/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/lib -L/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/lib -L. -L/Users/me/.rbenv/versions/2.2.3/lib -L. -L/Users/me/.rbenv/versions/2.2. 3/lib  -fstack-protector -L/usr/local/lib    /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/lib/     libexslt.a -lm -liconv -lpthread -lz /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/lib/libxml2.a /   Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/lib/libxslt.a -lm -liconv -lpthread -lz /Users/me/. rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/lib/libxml2.a -lruby-static -framework CoreFoundation /Users/me/. rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/lib/libexslt.a -lm -liconv -lpthread -lz /Users/me/.rbenv/       versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/lib/libxml2.a /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ nokogiri-1.6.7.rc3/ports/x86_64-apple-darwin11.4.2/libxslt/1.1.28/lib/libxslt.a -lm -liconv -lpthread -lz /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6. 7.rc3/ports/x86_64-apple-darwin11.4.2/libxml2/2.9.2/lib/libxml2.a -lpthread -ldl -lobjc  "
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.o)
  "_libiconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.o)
  "_libiconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Why doesn't nokogiri simply fetch and build its own version of libiconv like it does for libxml2? That would solve a number of problems.

**Comment by flavorjones** [comment] 2015-10-29 11:43
@mojca, thanks for commenting. I just said, above your comment, that we have a PR to fix this issue.

**Comment by mojca** [comment] 2015-10-29 12:26
Which PR and which problem? All I wanted to say is that I tried to apply https://github.com/sparklemotion/nokogiri/pull/1218/files, but my problem didn't go away yet. It is possible that the PR #1218 solves one of the many problems related to libiconv (mainly on 10.11), just not all of them yet.

**Comment by flavorjones** [comment] 2015-11-22 21:22
@mojca Can you please try building from source on master? If that doesn't address your issue, then let's examine what's going on with the patch from #1218 applied.

There is likely more than one issue going on, so I'm trying to be thorough and not conflate things.

**Comment by mojca** [comment] 2015-11-24 11:41
I tried the master and it still fails. What's the desired way to send you feedback / details?
~~~~~
checking for main() in -llzma... no
checking for xmlParseDoc() in libxml/parser.h... no
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
-----
libxml2 is missing.  Please locate mkmf.log to investigate how it is failing.
~~~~~

The file `~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-11/2.2.0-static/nokogiri-1.6.7.rc4/mkmf.log` says that the failure to find libxml

~~~~~
have_func: checking for xmlParseDoc() in libxml/parser.h... -------------------- no
~~~~~

is because of:

~~~~~
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.o)
  "_libiconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.o)
  "_libiconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.o)
ld: symbol(s) not found for architecture x86_64
~~~~~

while the beginning of `gem_make.out` reports that iconv has been successfully found:

~~~~~
checking for iconv.h... yes
checking for gzdopen() in -lz... yes
checking for iconv... yes
~~~~~

I was following the last section of http://buegling.com/blog/2015/4/26/building-nokogiri-on-os-x to build from master (without checking out any particular tag, just leaving the sources at master).

**Comment by mojca** [comment] 2015-11-24 11:50
As already mentioned above, one particularly suspicious part of the log is the following:

~~~~~
have_iconv?: checking for iconv... -------------------- yes

"clang -o conftest -I/Users/me/.rbenv/versions/2.2.3/include/ruby-2.2.0/x86_64-darwin11.0 -I/Users/me/.rbenv/versions/2.2.3/include/ruby-2.2.0/ruby/backward -I/Users/me/.rbenv/versions/2.2.3/include/ruby-2.2.0 -I. -I/Users/me/.rbenv/versions/2.2.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe  conftest.c  -L. -L/Users/me/.rbenv/versions/2.2.3/lib -L. -L/Users/me/.rbenv/versions/2.2.3/lib  -fstack-protector -L/usr/local/lib     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc  "
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _main in conftest-iiEMBa.o
  "_iconv_open", referenced from:
      _main in conftest-iiEMBa.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: 
 6: int main(void)
 7: {
 8:     iconv_t cd = iconv_open("", "");
 9:     iconv(cd, NULL, NULL, NULL, NULL);
10:     return EXIT_SUCCESS;
11: }
/* end */
~~~~~

There is no `-liconv` in the command that calls `clang`. I don't understand why the "iconv detection" succeeds in the first place. But calling `clang` manually on the same source file without `-liconv` fails for me as well. And if I add `-liconv` manually, the compilation succeeds. (But I don't know where that flag should be added in the configuration files, so I don't know how to fix the problem.)

**Comment by flavorjones** [comment] 2015-11-25 00:37
@mojca Great, thank you for the additional feedback. This is useful for us to narrow down the cause of your problem.

Worth noting, though, that patch #1218 (commit c623c84) does really address the original poster's problem in this issue, and so I'm going to close this ticket.

It sounds like you're describing a different problem, possibly the one being discussed at #1334. Can we pick up this thread there, where we're trying to reproduce an issue that sounds like what you're describing.

**Closed by flavorjones** 2015-11-25 00:37 UTC
Labels: iconv, osx
