### ISSUE TITLE
Nokogiri install issues on windows 2016 ruby 2.4.1p111 

### ISSUE THREAD

**Issue by oddtazz** [sparklemotion/nokogiri#1633] opened 2017-04-24 14:11 UTC
## If you're having trouble installing Nokogiri ...

**Have you tried following [the installation tutorial][tutorial]?**
Yes
I downloaded the latest version (1.7.1)
**What is the output of `gem install`?**

PS C:\opscode\chef\embedded\bin> .\gem.bat install nokogiri
ERROR:  Error installing nokogiri:
        nokogiri requires Ruby version < 2.4, >= 2.1.0.

**What are the contents of the `mkmf.log` file?**
Can't locate the `mkmf.log` file for nokogiri

**What operating system are you using?**
Windows 2016
ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by johnnyshields** [comment] 2017-04-30 10:48
Dupe of #1611

**Comment by flavorjones** [comment] 2017-04-30 21:41
@johnnyshields meant to say #1618. Please follow that ticket for updates.

**Closed by flavorjones** 2017-04-30 21:41 UTC
