### ISSUE TITLE
Nokogiri 1.10.9 libc errors

### ISSUE THREAD

**Issue by mortenolsrud** [sparklemotion/nokogiri#2009] opened 2020-03-04 10:06 UTC
**Describe the bug**
I ran bundle update to upgrade my puma dependency in the Rails project I'm working on, and saw that nokogiri-1.10.9 was also pulled in. When I tried running Rails after this through `bundle exec rails s -b 0.0.0.0` I get a stack trace which gives me this conclusion:

> /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so) - /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so (LoadError)

**Expected behavior**

I was unable to provide code due to proprietary code, but I expected Rails to start.

**Environment**
Nokogiri -v fails for 1.10.9:
```
LoadError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so) - /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `rescue in <top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:28:in `<top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `require'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `<top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/bin/nokogiri:23:in `load'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/bin/nokogiri:23:in `<top (required)>'
```
See env for 1.10.8 below

```
vagrant@tallinn-dev:~/tallinn$ bundle exec nokogiri -v
# Nokogiri (1.10.8)
    ---
    warnings: []
    nokogiri: 1.10.8
    ruby:
      version: 2.6.5
      platform: x86_64-linux
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10

```

**Comment by larskanis** [comment] 2020-03-04 12:33
> /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.28' not found

This error message indicates that the environment used for `gem install` (or `bundle update`) is different to the environment used to run Nokogiri (or your rails project). Could this be true?

Background is that Nokogiri tests for availability of certain functions while `gem install` and if they are available it makes use of these functions in the C extension. It is expected that the runtime environment has the same functions available, otherwise it fails with the above or other linker errors.

**Comment by mortenolsrud** [comment] 2020-03-04 12:39
Not so sure about that, as I used bundle update to upgrade, and used bundle exec rails s to run. That should ensure the environment is the same. 

Downgrading to version 1.10.8 with bundle update after pinning the version in the Gemfile solves the problem. Going back up re-introduces the error.

**Comment by flavorjones** [comment] 2020-03-04 15:46
Hi @mortenolsrud, sorry you're having a problem.

I'm unable to reproduce locally what you're seeing, unfortunately, so I need help understanding your configuration. Can you share both good and bad Gemfile+Gemfile.lock files?

Also: can you confirm whether you can `gem install nokogiri -v1.10.9` and get an operational gem? That is, does this problem manifest itself outside of your rails environment? And can you confirm that you've uninstalled 1.10.9 and re-installed with a completely local compilation?

**Comment by rally25rs** [comment] 2020-10-02 13:39
I had this same problem when using docker. In my case I discovered that my containers were trying to use a shared bundle cache (mounted as a volume), but containers were different linux distros. This could also happen if containers were trying to use the bundle cache of the host machine.

**Comment by flavorjones** [comment] 2020-10-02 18:15
@rally25rs Thanks for your comment! What you're saying makes sense (because essentially then Nokogiri was compile in a different environment than the one in which it's running).

Because the OP @mortenolsrud hasn't responded, and this seems like a reasonable hypothesis, I'm going to go ahead and close this issue. Feel free to comment if you'd like to continue the conversation!

**Closed by flavorjones** 2020-10-02 18:15 UTC
Labels: meta/user-help
