### ISSUE TITLE
Inconsistent parsing in CRuby vs JRuby

### ISSUE THREAD

**Issue by lephyrius** [sparklemotion/nokogiri#796] opened 2012-11-20 06:51 UTC
I tested this is IRB:
```
1.9.3p286 :002 > require 'nokogiri'
 => true 
1.9.3p286 :003 > Nokogiri::HTML::DocumentFragment.parse("")
 => #<Nokogiri::HTML::DocumentFragment:0x80829828 name="#document-fragment"> 
1.9.3p286 :004 > Nokogiri::HTML::DocumentFragment.parse(" ")
 => #<Nokogiri::HTML::DocumentFragment:0x80434038 name="#document-fragment"> 
```
```
jruby-1.7.0 :001 > require 'nokogiri'
 => true 
jruby-1.7.0 :002 > Nokogiri::HTML::DocumentFragment.parse("")
 => #<Nokogiri::HTML::DocumentFragment:0x7fa name="#document-fragment"> 
jruby-1.7.0 :003 > Nokogiri::HTML::DocumentFragment.parse(" ")
 => #<Nokogiri::HTML::DocumentFragment:0x7fe name="#document-fragment" children=[#<Nokogiri::XML::Text:0x7fc " ">]> 
```
As you can see. JRuby got children.
```
Nokogiri (1.5.5)
    ---
    warnings: []
    nokogiri: 1.5.5
    ruby:
      version: 1.9.3
      platform: java
      description: jruby 1.7.0 (1.9.3p203) 2012-10-22 ff1ebbe on Java HotSpot(TM) 64-Bit Server VM 1.6.0_26-b03-384-10M3425 [darwin-x86_64]
      engine: jruby
      jruby: 1.7.0

```

**Comment by flavorjones** [comment] 2016-02-17 05:07
This appears to be a dupe of #847 (or that is a dupe of this). In any case, it's not clear to me what the real-world impact of this is, and so I'm closing.

I'm happy to reconsider if you'll help me understand what affect this behavior is having.

**Closed by flavorjones** 2016-02-17 05:07 UTC
Labels: html, jruby
