### ISSUE TITLE
[bug] Nokogiri v1.16.0+ can't handle huge files

### ISSUE THREAD

**Issue by david-fluxster** [sparklemotion/nokogiri#3128] opened 2024-02-08 02:04 UTC
**Please describe the bug**
We have a test in our test suite that loads a large XML file (with a large amount of CSV data in it).

Nokogiri v1.15.5 can load and parse this file just fine. There are no errors
Nokogiri v1.16.0 cannot parse the file correctly, raising a validation_error (as an expected element is missing).

Confirmed that reducing the size of the CSV data component allows the code to work correctly (in v1.16.0).

**Help us reproduce what you're seeing**
We're using code straight from the docs:
```ruby
po = Nokogiri::XML::ParseOptions.new.huge.pedantic
xml = Nokogiri::XML::Document.parse(data, nil, nil, po)
```

We attempt to parse a large XML document (I'm not sure if I can include it here, due to privacy reasons)
With or without the "huge" option enabled, parsing a large XML file does not work (in v1.16.0).
```ruby
{:errors=>"15:0: ERROR: Element 'ReportResponse': Missing child element(s). Expected is ( Event ).", :syntax_errors=>nil}
```
(The ReportResponse element contains the large CSVData element that stops the parser from working correctly)

Schema in question looks something like this:
```
<xsd:complexType name="ReportResponse">
  <xsd:sequence>
    <xsd:element name="ReportParameters" type="BaseReportParameters"/>
    <xsd:element name="ResultBlock" type="MRBlockParameterType" minOccurs="0"/>
    <xsd:element name="ReportResults" type="BaseReportFormat" minOccurs="0"/>
    <xsd:element name="Event" type="Event" maxOccurs="unbounded"/>
  </xsd:sequence>
</xsd:complexType>
```

There is no difference in the given error message regardless of whether the "huge" option is given"

**Expected behavior**
We should be able to parse large XML files, provided the "huge" option is given.

**Environment**

```
# Nokogiri (1.16.2)
    ---
    warnings: []
    nokogiri:
      version: 1.16.2
      cppflags:
      - "-I/Users/david/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.2-x86_64-darwin/ext/nokogiri"
      - "-I/Users/david/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.2-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/david/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.2-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.3.0
      platform: x86_64-darwin23
      gem_platform: x86_64-darwin-23
      description: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin23]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.5
      loaded: 2.12.5
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      zlib: '1.3'
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```

**Additional context**
Does not seem to matter what the Ruby version is: tried with Ruby 3.0.6, and Ruby 3.3.0
Forcing the ruby platform does not change anything.
Nokogiri versions prior to v.1.16.0 work correctly (tested v1.13.10, v.1.14.5 and v1.15.5 and all work correctly).

In prior versions, NOT providing the "huge" flag would give the following error:
```ruby
{:errors=>nil, :syntax_errors=>"Error while processing XML (Nokogiri::XML::SyntaxError) 3440:1: FATAL: Extra content at the end of the document"}
```
So we're getting a different error message at least.

Not sure if I can provide the XML file due to privacy concerns. Let me know if you need help reproducing the issue, and I'll do my best to provide some XML that can replicate it

**Comment by flavorjones** [comment] 2024-02-08 03:03
@david-fluxster Thanks for reporting this, and sorry you're having this problem.

The most likely explanation is that this is a change in behavior in libxml2 (upstream). Nokogiri v1.16.0 updated libxml2 to 2.12.x which shipped a lot of changes around performance and memory consumption that may have broken something.

I'll spend some time tomorrow to try to reproduce what you're seeing. If I can repro, then I can `git bisect` and pretty quickly nail down what's changed.

**Comment by flavorjones** [comment] 2024-02-09 22:52
Also: can you please double-check that this is the code that's reproducing what you're seeing? Because the error message comes from libxml2's schema validation code (not the parsing code).

**Comment by david-fluxster** [comment] 2024-02-12 01:29
Ok, so there's nothing for you to do here, I would say.

I didn't do enough due diligence on my part, and there is an unusual (and unnecessary) double parsing of XML that's being done in our application, and the options weren't being provided during this secondary parsing. I can fix this without any changes to Nokogiri

I've created a repo which can reproduce this "issue": https://github.com/david-fluxster/nokogiri-bug-reproduction-1

I don't think it's important for you to look at this because it's actually easily fixable on our applications side, so shouldn't constitute a Nokogiri issue. However, it is interesting to note that there's still a difference in behaviour between prior versions. The script seems to work correctly on pre v1.16.0 versions.

Thanks for investigating this. Apologies for any time wasted. I think I'm satisfied that this issue can be closed

**Comment by flavorjones** [comment] 2024-02-12 03:15
@david-fluxster Thanks for closing the loop. As I mentioned above, there was a lot of work done upstream in libxml 2.12 -- including improved error handling! -- that could affect your app. One possibility is that it _should_ have been raising an error in previous versions and wasn't.

Anyway. If you find you need anything from me, let me know!

**Closed by flavorjones** 2024-02-12 03:15 UTC
Labels: state/needs-triage

**Comment by bcgraham** [comment] 2024-02-21 16:33
@david-fluxster Would it be possible for you to bring back your bug reproduction repository? We're getting this and it might save us some time.

**Comment by david-fluxster** [comment] 2024-02-21 23:05
@bcgraham I've made the repo public again. Hope this helps you
