### ISSUE TITLE
[bug] XML entity codes are printed along with expansion in to_s on JRuby

### ISSUE THREAD

**Issue by i-h8-github** [sparklemotion/nokogiri#3270] opened 2024-07-03 00:26 UTC
**Please describe the bug**

On JRuby, calling `to_s` on an element with an entity reference will print the code and its expansion, as opposed to just the XML contents of the element verbatim as in MRI.

**Help us reproduce what you're seeing**

`tst.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Test [
<!ENTITY t "Test">
]>
<pos>&t;</pos>
```

`tst.rb:`
```ruby
require 'nokogiri'
doc = Nokogiri::XML(File.open('tst.xml'))
doc.xpath("//pos").each do |p| puts p end
```
`output:`
```
$ jruby tst.rb
<pos>&t;Test</pos>
```
**Expected behavior**

```
$ ruby tst.rb
<pos>&t;</pos>
```

**Environment**

```
# Nokogiri (1.13.10)
    ---
    warnings: []
    nokogiri:
      version: 1.13.10
    ruby:
      version: 2.6.8
      platform: java
      gem_platform: universal-java-11
      description: jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM
        11.0.23+9-post-Ubuntu-1ubuntu122.04.1 on 11.0.23+9-post-Ubuntu-1ubuntu122.04.1
        +jit [x86_64-linux]
      engine: jruby
      jruby: 9.3.9.0
    other_libraries:
      xerces: Xerces-J 2.12.2
      nekohtml: NekoHTML 1.9.22.noko2
```

**Additional context**

None.

**Comment by flavorjones** [comment] 2024-07-03 02:03
Hi, thanks for reporting this. I've reproduced on nokogiri main:

```ruby
#! /usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "nokogiri", path: "."
end

pp Nokogiri::VERSION_INFO

xml = <<~XML
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE Test [
  <!ENTITY t "Test">
  ]>
  <pos>&t;</pos>
XML

doc = Nokogiri::XML(xml)
pp doc
doc.xpath("//pos").each do |p|
  puts p.to_xml
end
```

**Comment by flavorjones** [comment] 2024-07-03 02:29
I am totally shocked that this bug exists ... I think it's been around since the beginnings of the JRuby implementation. Bonkers. How did nobody find this before? And: why don't we have test coverage for this? Bonkers.

This is going to be straightforward to fix, I just need to make sure we do the right thing based on the `NOENT` parse option, and that we have adequate test coverage.

**Comment by flavorjones** [comment] 2024-07-03 13:24
Proposed fix is in #3272, which will be shipped in v1.17.0 later this month.

**Closed** 2024-07-03 14:07 UTC
Labels: platform/jruby, topic/entities

**Comment by i-h8-github** [comment] 2024-07-04 03:02
Sorry, I meant where can I go to see the actual code which solved this. Purely to sate my own curiosity.

**Comment by flavorjones** [comment] 2024-07-04 12:25
I am trying to tell you that by clicking on the link that's in my last two messages you will see the code that was changed. Or click on either of the links above that say "closed this as completed in ..."

**Comment by i-h8-github** [comment] 2024-07-04 14:48
Sorry, I don't use GitHub much.

Thank you for your time and effort. I really appreciate your work toward making this improvement and am looking forward to being able to use it soon.

**Comment by flavorjones** [comment] 2024-07-05 02:01
I appreciate you reporting this! As I said, I'm shocked that nobody has ever reported it before.
