### ISSUE TITLE
Nokogiri and OpenBSD

### ISSUE THREAD

**Issue by chapmajs** [sparklemotion/nokogiri#1885] opened 2019-04-04 02:48 UTC
Automatic installation of nokogiri fails on OpenBSD. Tested with 5.8, 6.2, 6.3, and 6.4. Even with `libiconv` installed, nokogiri fails to find it due to OpenBSD sticking the lib in `/usr/local/lib`.

To reproduce, do `gem install nokogiri -v '1.10.2'` on OpenBSD. Do not specify `--with-iconv-lib`.  Yes, you can make it work with a manual `--with-iconv-lib` but I'm tired of having to SSH into various servers and build manually every time I upgrade nokogiri.

I'd like to fix autodetection of `libiconv` paths on OpenBSD. Pretty sure I've got a quick fix for it, but I'm unable to test due to the lack of gemspec file (yes, I read `Y_U_NO_GEMSPEC.md` and understand/appreciate when it's not included). I understand the risks (can't be worse than developing kernel drivers, right? :P ). Where can I get a gemspec for testing?

Also:

    * [ ] get openbsd / freebsd / etc. people to donate worker machines

I am happy to donate OpenBSD machine time for development. I can even provide it on non-Intel/AMD architectures (SPARC64, Alpha, etc.).

**Comment by flavorjones** [comment] 2019-04-04 18:58
Hi! Thanks for opening this issue. I wasn't aware of OpenBSD issues, so I appreciate you calling it out.

You can generate an ephemeral gemfile by making sure you have the `hoe-gemspec` gem installed, and running `rake gem:spec`. Hopefully this will allow you to do the testing you need; if not, an alternative is to simply run `rake gem` to build a gem and install it locally.

An OpenBSD worker for our Concourse CI pipelines would be **uhmerzing**. Maybe let's get through this issue and then start a separate thread on that topic?

**Comment by flavorjones** [comment] 2020-02-22 19:43
@chapmajs I'm curious if you got past your issues? And if so, are you willing to send a PR?

I'm also curious if you're still serious about helping test on OpenBSD? I'd happily help set up a Concourse worker if this is still a pain point for you.

**Comment by chapmajs** [comment] 2020-02-23 01:03
I'm still manually building the dependency on the servers; I ended up partially automating it since the fix turned out to be less straightforward than I thought. I need to revisit it but haven't had time.

Definitely still serious about helping with OpenBSD testing.

**Comment by jmettraux** [comment] 2020-05-06 09:04
Adding a piece of information for people ending up here upon searching "openbsd nokogiri libiconv".

On OpenBSD 6.6, I ended up doing
```
$ bundle config build.nokogiri --use-system-libraries
$ bundle install
```
to circumvent the build complaining about not finding libiconv

I found the "inspiration" at https://nokogiri.org/tutorials/installing_nokogiri.html

Thanks!

**Comment by flavorjones** [comment] 2020-05-06 13:33
@jmettraux Thanks for this.

@chapmajs Thanks for offering to help with OpenBSD testing. I'm not sure what to ask for -- our CI system (Concourse) doesn't look like it supports OpenBSD workers so I have to give a think here on what I'd need beyond what a Virtualbox VM would provide.

**Comment by flavorjones** [comment] 2020-05-23 18:48
I've set up an openbsd virtualbox environment and have reproduced this issue in openbsd 6.6.

The key bit from the logs:

```
have_iconv?: checking for iconv using --with-opt-* flags... -------------------- yes

"cc -o conftest -I/usr/local/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/x86_64-openbsd6.6 -I/usr/local/rvm/rubies/ruby-2
.7.0/include/ruby-2.7.0/ruby/backward -I/usr/local/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0 -I.  -I/usr/local/include 
  -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -fPIC  -I /usr/local/include -g -DXP_UNIX conftest.c  -L. -L/usr/local/rvm/rubies/ruby-2.7.0/lib -Wl,-rpath,/usr/local/rvm/rubies/ruby-2.7.0/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -fstack-protector-strong -Wl,-E -L/usr/local/lib  -Wl,-rpath,/usr/local/lib     -Wl,-rpath,/usr/local/rvm/rubies/ruby-2.7.0/lib -L/usr/local/rvm/rubies/ruby-2.7.0/lib -lruby  -lm   -lc "
ld: error: undefined symbol: libiconv_open
>>> referenced by conftest.c:8
>>>               /tmp/conftest-12693a.o:(main)

ld: error: undefined symbol: libiconv
>>> referenced by conftest.c:9
>>>               /tmp/conftest-12693a.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: 
 6: int main(void)
 7: {
 8:     iconv_t cd = iconv_open("", "");
 9:     iconv(cd, NULL, NULL, NULL, NULL);
10:     return EXIT_SUCCESS;
11: }
/* end */
```

Interestingly, when I build and test it with `rake compile test`, everything works OK.

Also tagging @jeremyevans since I believe he maintains the Nokogiri port for OpenBSD (or used to), in case he has insight into how to address this.

**Comment by flavorjones** [comment] 2020-05-23 19:04
I've set up an OpenBSD testing environment (via Virtualbox) and I'm seeing an error ... but I'm not sure it's the same one as the original post describes:

```
Running 'compile' for libxml2 2.9.10... ERROR, review '/usr/local/rvm/gems/ruby-2.7.0/gems/nokogiri-1.11.0.rc2/ext/nokogiri/tmp/x86_64-unknown-openbsd6.6/ports/libxml2/2.9.10/compile.log' to see what happened. Last lines are:
========================================================================
  CC       xmlregexp.lo
  CC       xmlschemas.lo
  CC       xmlschemastypes.lo
  CC       xmlunicode.lo
  CC       xmlreader.lo
  CC       relaxng.lo
  CC       dict.lo
  CC       SAX2.lo
  CC       xmlwriter.lo
  CC       legacy.lo
  CC       chvalid.lo
  CC       pattern.lo
  CC       xmlsave.lo
  CC       xmlmodule.lo
  CC       schematron.lo
  CC       xzlib.lo
make: don't know how to make libxml2.la (prerequisite of: all-am)
Stop in .
*** Error 1 in . (Makefile:1504 'all-recursive')
*** Error 2 in /usr/local/rvm/gems/ruby-2.7.0/gems/nokogiri-1.11.0.rc2/ext/nokogiri/tmp/x86_64-unknown-openbsd6.6/ports/libxml2/2.9.10/libxml2-2.9.10 (Makefile:893 'all')
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.7.0/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/usr/local/rvm/gems/ruby-2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:405:in `block in execute': Failed to complete compile task (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:376:in `chdir'
	from /usr/local/rvm/gems/ruby-2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:376:in `execute'
	from /usr/local/rvm/gems/ruby-2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:115:in `compile'
	from /usr/local/rvm/gems/ruby-2.7.0/gems/mini_portile2-2.5.0/lib/mini_portile2/mini_portile.rb:154:in `cook'
	from extconf.rb:369:in `block (2 levels) in process_recipe'
	from extconf.rb:261:in `block in chdir_for_build'
	from extconf.rb:260:in `chdir'
	from extconf.rb:260:in `chdir_for_build'
	from extconf.rb:368:in `block in process_recipe'
	from extconf.rb:266:in `tap'
	from extconf.rb:266:in `process_recipe'
	from extconf.rb:571:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.7.0/extensions/x86_64-openbsd-6.6/2.7.0/nokogiri-1.11.0.rc2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.7.0/gems/nokogiri-1.11.0.rc2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.7.0/extensions/x86_64-openbsd-6.6/2.7.0/nokogiri-1.11.0.rc2/gem_make.out
```

Interestingly, I'm able to compile and pass the test suite when running `rake compile test` in the source directory. Pinging @jeremyevans as the OpenBSD port maintainer to see if he has any insight.

**Comment by flavorjones** [comment] 2020-05-23 19:07
More interesting: I got this to compile and run via `rake compile test` earlier, but now I'm having the same issue as that shown at `gem install nokogiri` time.

Successful run:

```
/nokogiri/test/helper.rb:29: version info: {"warnings"=>[], "nokogiri"=>"1.11.0.rc2", "ruby"=>{"version"=>"2.7.0", "platform"=>"x86_64-openbsd6.6", "description"=>"ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-openbsd6.6]", "engine"=>"ruby"}, "libxml"=>{"source"=>"packaged", "patches"=>["0001-Revert-Do-not-URI-escape-in-server-side-includes.patch", "0002-Remove-script-macro-support.patch", "0003-Update-entities-to-remove-handling-of-ssi.patch", "0004-libxml2.la-is-in-top_builddir.patch", "0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch"], "compiled"=>"2.9.10", "loaded"=>"2.9.10"}, "libxslt"=>{"source"=>"packaged", "patches"=>[], "compiled"=>"1.1.34", "loaded"=>"1.1.34"}}
Run options: --seed 49445

# Running:

................................................................................................................S....................S........................................................................................................................S...S...................................................................................................................................................S.......S.......................................................................................................................................................................................................................................................................S......................................................................................................................................................................................................................................................................................................................................................S........................................................................SS................................................................................................................................................................................................................................................................................................................................................................................................................................................

Fabulous run in 25.197901s, 60.6400 runs/s, 169.3792 assertions/s.

1528 runs, 4268 assertions, 0 failures, 0 errors, 10 skips
```

and now failure run:

```
Running 'compile' for libxml2 2.9.10... ERROR, review '/nokogiri/tmp/x86_64-openbsd6.6/nokogiri/2.7.0/tmp/x86_64-unknown-openbsd6.6/ports/libxml2/2.9.10/compile.log' to see what happened. Last lines are:
========================================================================
  CC       xmlregexp.lo
  CC       xmlschemas.lo
  CC       xmlschemastypes.lo
  CC       xmlunicode.lo
  CC       xmlreader.lo
  CC       relaxng.lo
  CC       dict.lo
  CC       SAX2.lo
  CC       xmlwriter.lo
  CC       legacy.lo
  CC       chvalid.lo
  CC       pattern.lo
  CC       xmlsave.lo
  CC       xmlmodule.lo
  CC       schematron.lo
  CC       xzlib.lo
make: don't know how to make libxml2.la (prerequisite of: all-am)
```

:thinking:

**Comment by flavorjones** [comment] 2020-05-23 19:13
I've managed to set up an OpenBSD testing environment and ... I'm getting unreliable results at the moment. Going to rebuild it in a repeatable way and see if I can stabilize it.

**Comment by jeremyevans** [comment] 2020-05-23 19:38
Not sure if this helps, but on OpenBSD, the nokogiri package is built using `--use-system-libraries --with-xml2-include=/usr/local/include/libxml2`.  The package is currently on 1.10.8, but I can update it to 1.11.0 after it is released.

**Comment by flavorjones** [comment] 2020-05-23 19:39
OK - I'm unable to reproduce this at the moment. I'm running OpenBSD 6.6. I've provisioned the box with this script:

```sh
    # install rvm
    pkg_add gnupg-2.2.12p0
    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable
    source /etc/profile.d/rvm.sh
    usermod -G rvm vagrant

    # install ruby and build-essentials
    rvm install ruby-2.7
```

And then I'm able to install the gem:

```
-bash-5.0$ gem install nokogiri
Fetching nokogiri-1.10.9.gem
Fetching mini_portile2-2.4.0.gem
Successfully installed mini_portile2-2.4.0
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.9
Parsing documentation for mini_portile2-2.4.0
Installing ri documentation for mini_portile2-2.4.0
Parsing documentation for nokogiri-1.10.9
Installing ri documentation for nokogiri-1.10.9
Done installing documentation for mini_portile2, nokogiri after 7 seconds
2 gems installed
-bash-5.0$ 
-bash-5.0$ nokogiri -v
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.7.0
      platform: x86_64-openbsd6.6
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-openbsd6.6]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/usr/local/rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/ports/x86_64-unknown-openbsd6.6/libxml2/2.9.10"
      libxslt_path: "/usr/local/rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/ports/x86_64-unknown-openbsd6.6/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

What am I doing differently than you, @chapmajs?

**Comment by flavorjones** [comment] 2022-02-27 17:17
Closing. If someone can help me reproduce an installation issue, please open a new issue. Thanks.

**Closed by flavorjones** 2022-02-27 17:17 UTC
Labels: needs/more-info, platform/openbsd
