### ISSUE TITLE
[install]

### ISSUE THREAD

**Issue by louis-guillaume** [sparklemotion/nokogiri#2932] opened 2023-07-17 14:56 UTC
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [ x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.4.10
Fetching mini_portile2 2.8.2
Fetching racc 1.7.1
Installing mini_portile2 2.8.2
Installing racc 1.7.1 with native extensions
Fetching nokogiri 1.15.3
Installing nokogiri 1.15.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri
/opt/pkg/bin/ruby32 extconf.rb --with-ldflags\=-L.\ -L/opt/pkg/lib\ -L/usr/lib
--with-xml2-include\=/opt/pkg/include/libxml2
checking for whether -std=c99 is accepted as CFLAGS... no
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... no
checking for whether -O2 is accepted as CFLAGS... no
checking for whether -g is accepted as CFLAGS... no
checking for whether -Winline is accepted as CFLAGS... no
checking for whether -Wmissing-noreturn is accepted as CFLAGS... no
checking for whether -Wshorten-64-to-32 is accepted as CFLAGS... no
checking for whether -Wno-error=unused-command-line-argument-hard-error-in-future is accepted as
CFLAGS... no
checking for whether -Wno-unknown-warning-option is accepted as CFLAGS... no
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
checking for iconv.h... yes
Using mini_portile version 2.8.2
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.11.4.
Configuration options: --host\=x86_64-apple-darwin22 --enable-static --disable-shared
--libdir\=/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxml2/2.11.4/lib
--with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n
--with-debug --with-threads --disable-shared --enable-static RANLIB\=/usr/bin/ranlib AR\=/usr/bin/ar
CPPFLAGS\= CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-update-config.guess-and-config.sub-for-libxml2.patch
  - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.11.4.tar.xz into tmp/x86_64-apple-darwin22/ports/libxml2/2.11.4... OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0001-Remove-script-macro-support.patch...
OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0002-Update-entities-to-remove-handling-of-ssi.patch...
OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0003-libxml2.la-is-in-top_builddir.patch...
OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0009-allow-wildcard-namespaces.patch...
OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0010-update-config.guess-and-config.sub-for-libxml2.patch...
OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxml2/0011-rip-out-libxml2-s-libc_single_threaded-support.patch...
OK
Running 'configure' for libxml2 2.11.4... OK
Running 'compile' for libxml2 2.11.4... OK
Running 'install' for libxml2 2.11.4... OK
Activating libxml2 2.11.4 (from
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxml2/2.11.4)...
Using mini_portile version 2.8.2
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxslt-1.1.38.
Configuration options: --host\=x86_64-apple-darwin22 --enable-static --disable-shared
--libdir\=/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxslt/1.1.38/lib
--disable-dependency-tracking --without-python --without-crypto --with-debug
--with-libxml-prefix\=/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxml2/2.11.4
--disable-shared --enable-static RANLIB\=/usr/bin/ranlib AR\=/usr/bin/ar CFLAGS\=-O2\
-U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-update-config.guess-and-config.sub-for-libxslt.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Extracting libxslt-1.1.38.tar.xz into tmp/x86_64-apple-darwin22/ports/libxslt/1.1.38... OK
Running git apply with
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/patches/libxslt/0001-update-config.guess-and-config.sub-for-libxslt.patch...
OK
Running 'configure' for libxslt 1.1.38... OK
Running 'compile' for libxslt 1.1.38... OK
Running 'install' for libxslt 1.1.38... OK
Activating libxslt 1.1.38 (from
/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxslt/1.1.38)...
checking for whether -DNOKOGIRI_PACKAGED_LIBRARIES is accepted as CPPFLAGS... no
xml2-config cflags:
-I/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxml2/2.11.4/include/libxml2
checking for whether -DNOKOGIRI_LIBXML2_PATCHES="\"0001-Remove-script-macro-support.patch
0002-Update-entities-to-remove-handling-of-ssi.patch 0003-libxml2.la-is-in-top_builddir.patch
0009-allow-wildcard-namespaces.patch 0010-update-config.guess-and-config.sub-for-libxml2.patch
0011-rip-out-libxml2-s-libc_single_threaded-support.patch\"" is accepted as CPPFLAGS... no
checking for -llzma... yes
xslt-config cflags:
-I/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxml2/2.11.4/include/libxml2
-I/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ports/x86_64-darwin22/libxslt/1.1.38/include
checking for whether
-DNOKOGIRI_LIBXSLT_PATCHES="\"0001-update-config.guess-and-config.sub-for-libxslt.patch\"" is
accepted as CPPFLAGS... no
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
Using mini_portile version 2.8.2
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libgumbo-1.0.0-nokogiri.
Configuration options: --disable-shared --enable-static CFLAGS\=-fPIC
Copying gumbo-parser files into
tmp/x86_64-apple-darwin22/ports/libgumbo/1.0.0-nokogiri/gumbo-parser...
Running 'compile' for libgumbo 1.0.0-nokogiri... OK
Activating libgumbo 1.0.0-nokogiri (from ports/x86_64-darwin22/libgumbo/1.0.0-nokogiri)...
checking for whether
-I/opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri/ports/x86_64-darwin22/libgumbo/1.0.0-nokogiri/include
is accepted as CPPFLAGS... no
checking for gumbo_parse_with_options() in nokogiri_gumbo.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
checking for rb_gc_location()... yes
checking for rb_category_warning()... yes
checking for whether -DNOKOGIRI_OTHER_LIBRARY_VERSIONS="\"libgumbo:1.0.0-nokogiri\"" is accepted as
CPPFLAGS... no
creating Makefile

current directory: /opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20230716-69168-3r8sg6 sitelibdir\=./.gem.20230716-69168-3r8sg6
clean

current directory: /opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20230716-69168-3r8sg6 sitelibdir\=./.gem.20230716-69168-3r8sg6
compiling gumbo.c
clang: warning: argument unused during compilation: '-diag-disable=175,188,1684,2259,2312'
[-Wunused-command-line-argument]
gumbo.c:32:10: fatal error: 'nokogiri_gumbo.h' file not found
#include "nokogiri_gumbo.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [gumbo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/sandbox/ngtest/bundle/ruby/3.2.0/gems/nokogiri-1.15.3 for
inspection.
Results logged to
/opt/sandbox/ngtest/bundle/ruby/3.2.0/extensions/x86_64-darwin-22/3.2.0/nokogiri-1.15.3/gem_make.out

  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:51:in `block in make'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `each'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `make'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:41:in `build'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in build_extensions'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  /opt/pkg/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  /opt/pkg/lib/ruby/3.2.0/rubygems/installer.rb:852:in `build_extensions'
  /opt/pkg/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /opt/pkg/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/pkg/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  /opt/pkg/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /opt/pkg/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/pkg/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /opt/pkg/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /opt/pkg/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /opt/pkg/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /opt/pkg/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /opt/pkg/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /opt/pkg/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.15.3), and Bundler cannot continue.

In Gemfile:
  nokogiri
```

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

```
the output of "nokogiri -v" goes here
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

mkmf.log is too big for this form. But we have many of these errors:

```
clang: error: argument unused during compilation: '-diag-disable=175,188,1684,2259,2312' [-Werror,-Wunused-command-line-argument]
```

And one iconv linker error (this may be the whole problem)...

```
try_link_iconv: checking for iconv... -------------------- yes

DYLD_FALLBACK_LIBRARY_PATH=.:/opt/pkg/lib "clang -o conftest -I/opt/pkg/include/ruby-3.2.0/x86_64-darwin22 -I/opt/pkg/include/ruby-3.2.0/ruby/backward -I/opt/pkg/include/ruby-3.2.0 -I. -I/opt/pkg/include -D_REENTRANT -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT   -O2 -I/opt/pkg/include -D_REENTRANT -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -diag-disable=175,188,1684,2259,2312 -Wundef -fno-common -pipe conftest.c  -L. -L/opt/pkg/lib -L. -L/opt/pkg/lib -L/usr/lib     -lruby32.3.2.2  -lpthread -lpthread "
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _main in conftest-8b1441.o
  "_libiconv_open", referenced from:
      _main in conftest-8b1441.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: int main(void)
 6: {
 7:     iconv_t cd = iconv_open("", "");
 8:     iconv(cd, NULL, NULL, NULL, NULL);
 9:     return EXIT_SUCCESS;
10: }
/* end */
```

If you're using Bundler:
- what is the output from `bundle version`?

```
$ bundle version
Bundler version 2.4.10 (2023-07-17 commit unknown)
```

- what is the output from `bundle config`? (Take care to redact any credentials)

```
$ bundle config
Settings are listed in order of priority. The top value will be used.
bin
Set for your local app (/opt/sandbox/ngtest/.bundle/config): "./bin"

build.nokogiri
Set for your local app (/opt/sandbox/ngtest/.bundle/config): "--with-ldflags='-L. -L/opt/pkg/lib -L/usr/lib' --with-xml2-include=/opt/pkg/include/libxml2"

build.racc
Set for your local app (/opt/sandbox/ngtest/.bundle/config): "--with-ldflags=-L. -L/usr/lib -L/opt/pkg/lib"

force_ruby_platform
Set for your local app (/opt/sandbox/ngtest/.bundle/config): true

path
Set for your local app (/opt/sandbox/ngtest/.bundle/config): "./bundle"

set
Set for the current user (/Users/louis/.bundle/config): "--local path .bundle"
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`

```
$ clang -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

If Linux or a BSD variant, please note:
- the distro you're using
- the output of `uname -a`
- the contents of `/etc/lsb-release`.

```
$ uname -a
Darwin dhcp-223.xxxxxxxx 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
```

If Windows, please note:
- whether you're installing the precompiled gems, or compiling yourself with DevKit
- the version of RubyInstaller you've installed
- or if you're not using RubyInstaller, how did you install Ruby?

**Comment by flavorjones** [comment] 2023-07-17 15:50
@louis-guillaume Sorry you're having trouble. I'll try to help.

I see that you've made quite a few tweaks in this environment to try to get Nokogiri to build, including setting some linker flags. Have you also set any environment variables like `CFLAGS` or `LDFLAGS`? (The mkmf.log might have told me this but you didn't include it.)

Can I ask why you're not using the precompiled gem, which would avoid all of these compilation and linking issues?

**Comment by louis-guillaume** [comment] 2023-07-17 18:34
@flavorjones  - Honestly not sure where the `--diag-disable` is coming from. I did add the `--with-ldflags` and `--with-xml-2-include`. The latter was because the build was finding libxml headers elsewhere (probably in the base system). The ldflags - not sure I remember why - but I also needed it for the racc build. I'm not setting CFLAGS  or LDFLAGS in the environment.

mkmf.log was too big to include in the problem report. I did include a couple excerpts, though, where it seemed to be reporting significant errors. Looks like I can add it as an attachment though....

[mkmf.log](https://github.com/sparklemotion/nokogiri/files/12072833/mkmf.log)


The main reason I'm not using the precompiled gem is that I'm building for mixed platform deployment and don't want to depend on system gems. So my dev machine is MacOS, but will deploy to NetBSD and/or Linux hosts for production. As long as I have the correct ruby version and bundler, I'm expecting to have the target system re-bundle in place as part of the deployment. 

LMK I can provide any other details. Thanks for looking!

**Comment by flavorjones** [comment] 2023-07-17 18:52
> don't want to depend on system gems

I'm not sure I understand this point. The precompiled gems use the same version of libxml2 and libxslt on all platforms; and these will be the same versions compiled on the platforms that don't support it (e.g., NetBSD). I strongly recommend you take a hard look at using the precompiled gems, because this is exactly the problem they were created to solve.

You should look at your system environment to determine where the `--diag-disable` flag is coming from, because something is injecting properties into your compile and link flags, and I'm not sure I can help until you can reproduce this issue with a clean environment (no bundler flags, no unknown or unwanted compiler or linker flags).

**Comment by flavorjones** [comment] 2023-07-17 18:55
You may want to take a look at `RbConfig::CONFIG["CFLAGS"]` and `["LDFLAGS"]` to see if some of these flags are coming from your ruby build.

**Comment by flavorjones** [comment] 2023-07-17 21:37
> Now I have no overrides in .bundle/config for nokogiri or racc and they build just fine

That's good news! Thanks for closing the loop with us. :heart:

**Closed by flavorjones** 2023-07-17 21:37 UTC
Labels: topic/installation
