### ISSUE TITLE
#xpath performance

### ISSUE THREAD

**Issue by etm** [sparklemotion/nokogiri#760] opened 2012-09-12 22:42 UTC
about 1/3 of the runtime of #xpath is spent allocating XPathContext. Not sure, but do you think caching the context could lead to bad situations? Caching would improve performance a lot.

Example (can be inserted into #xpath)

```
 @oldns ||= {}
 if @oldns == ns
   @ctx ||= XPathContext.new(self)
 else
   @ctx = XPathContext.new(self)
   @ctx.register_namespaces(ns)
  @oldns = ns
 end
...
@ctx.evaluate(....)
```

Note: adding and initializing @ctx and @oldns in the constructor is bad, as nodes that never need a ctx are created quite often, and thus this would degrade performance again.

cheers,

eTM

**Comment by Tristramg** [comment] 2015-01-27 17:09
@jvshahid correct me if I’m wrong, but #1004 only concerns JRuby, while @etm was talking about mri.

I observed also a speedup with the suggested monkey patching, nokogiri 1.6.6.2 and ruby mri 2.1.0

**Comment by etm** [comment] 2015-01-27 22:29
Yes. I'm talking about MRI. And the (preceived) problem still persists. And its not primarily about speedup (which could be reaped after solving this). Its about the behaviour of the following code:

    require 'rubygems'
    require 'nokogiri'
    
    doc = Nokogiri.XML("<foo><baz/><baz><bar name='test'/></baz></foo>")
    xpa = Nokogiri::XML::XPathContext.new(doc.root)

    p xpa.evaluate('//baz').length # => 2
    p xpa.evaluate('baz').length # => 2
    p xpa.evaluate('foo').length # => 0 
    p xpa.evaluate('//@name').length # => 1
    p xpa.evaluate('//baz').length # => 2
    p xpa.evaluate('baz').length # => 0
    p xpa.evaluate('foo').length # => 1  

This code should output 2201220, it does output 2201201. I still think the results of the point at a bug.

**Comment by flavorjones** [comment] 2015-01-28 04:17
Urgh, OK, reopening.

@etm - I'm curious why no objections were raised when this ticket was closed. Honestly, I thought this had been solved, and apologize for the confusion.

**Comment by etm** [comment] 2015-01-28 09:25
Sorry, entirely my fault, must have missed the mail notification that it was closed :-) It bugs me not that much that I check it back regularely. After all, it only occurs in a code path, that is currently not used that way in nokogiri, so this is understandably not high priority.

**Comment by flavorjones** [comment] 2015-02-09 16:57
@etm There is definitely some weirdness going on here. Part of the issue is that libxml2 stores state in XPathContext, meaning that you shouldn't re-use it unless you know what you're doing. Calling `Node#xpath` will create a new context each time to avoid these stateful behaviors.

This is also probably the behavior that's causing slowness.

That aside, there's still something else going on in the JRuby port that I don't fully understand yet; I need to isolate the behavior with test cases. Wish I could be more specific at this time.

**Comment by flavorjones** [comment] 2024-07-02 13:36
For whatever it's worth the test case provided above now works properly on modern libxml2/nokogiri:

```
#! /usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "nokogiri"
end

RUBY_VERSION # => "3.3.3"
Nokogiri::VERSION_INFO
# => {"warnings"=>[],
#     "nokogiri"=>
#      {"version"=>"1.16.6",
#       "cppflags"=>
#        ["-I/home/flavorjones/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-x86_64-linux/ext/nokogiri",
#         "-I/home/flavorjones/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-x86_64-linux/ext/nokogiri/include",
#         "-I/home/flavorjones/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-x86_64-linux/ext/nokogiri/include/libxml2"],
#       "ldflags"=>[]},
#     "ruby"=>
#      {"version"=>"3.3.3",
#       "platform"=>"x86_64-linux",
#       "gem_platform"=>"x86_64-linux",
#       "description"=>
#        "ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]",
#       "engine"=>"ruby"},
#     "libxml"=>
#      {"source"=>"packaged",
#       "precompiled"=>true,
#       "patches"=>
#        ["0001-Remove-script-macro-support.patch",
#         "0002-Update-entities-to-remove-handling-of-ssi.patch",
#         "0003-libxml2.la-is-in-top_builddir.patch",
#         "0009-allow-wildcard-namespaces.patch",
#         "0010-update-config.guess-and-config.sub-for-libxml2.patch",
#         "0011-rip-out-libxml2-s-libc_single_threaded-support.patch"],
#       "memory_management"=>"ruby",
#       "iconv_enabled"=>true,
#       "compiled"=>"2.12.8",
#       "loaded"=>"2.12.8"},
#     "libxslt"=>
#      {"source"=>"packaged",
#       "precompiled"=>true,
#       "patches"=>
#        ["0001-update-config.guess-and-config.sub-for-libxslt.patch"],
#       "datetime_enabled"=>true,
#       "compiled"=>"1.1.39",
#       "loaded"=>"1.1.39"},
#     "other_libraries"=>{"zlib"=>"1.3.1", "libgumbo"=>"1.0.0-nokogiri"}}

doc = Nokogiri.XML("<foo><baz/><baz><bar name='test'/></baz></foo>")
xpa = Nokogiri::XML::XPathContext.new(doc.root)

xpa.evaluate('//baz').length # => 2
xpa.evaluate('baz').length # => 2
xpa.evaluate('//@name').length # => 1
xpa.evaluate('baz').length # => 2
xpa.evaluate('//baz').length # => 2
xpa.evaluate('foo').length # => 0
```

**Comment by flavorjones** [comment] 2024-07-02 13:43
As for improving the performance of XPath queries, yes, we could re-use `XPathContext` objects but we do need to be careful about thread safety.

If someone wants to take a stab at writing something like an xpath-context-pool I'd happily review a PR.

**Comment by flavorjones** [comment] 2024-07-02 14:21
I've opened a new issue to drive exploring XPath performance with respect to re-using context objects: https://github.com/sparklemotion/nokogiri/issues/3266

Closing this one in preference to that one.

**Closed by flavorjones** 2024-07-02 14:21 UTC
Labels: topic/performance

**Comment by kivikakk** [comment] 2024-07-02 14:25
What a blast from the past!
