### ISSUE TITLE
"Tutorials" link on https://nokogiri.org/ is broken

### ISSUE THREAD

**Issue by shlomif** [sparklemotion/nokogiri#1958] opened 2019-12-15 11:48 UTC
**Describe the bug**

The "Tutorials" hyperlink on https://nokogiri.org/ is broken (FF and chromium on mageia linux v8).

**Comment by flavorjones** [comment] 2020-01-06 14:07
Hi @shlomif, thanks for reporting this. For future reference, docs bugs should be reported at https://github.com/sparklemotion/nokogiri.org

I unfortunately am not seeing anything wrong with the site. Here's an animated gif showing you what I'm seeing:

![Peek 2020-01-06 09-06](https://user-images.githubusercontent.com/8207/71822844-e5971200-3063-11ea-90d9-1ce87bd3f72f.gif)

Can you help me understand what you're seeing and why you think something is broken?

**Comment by shlomif** [comment] 2020-01-06 15:18
@flavorjones : I mean the "Tutorial" link under the "Links" header - see https://www.shlomifish.org/Files/files/video/nokogiri-org-2020-01-06_17.12.46.webm for a demo. thanks!

**Comment by flavorjones** [comment] 2020-01-27 14:09
Hi - thanks for reporting this. It seems to be a duplicate of https://github.com/sparklemotion/nokogiri.org/issues/24 and so I'm going to close this in favor of that one.

**Closed by flavorjones** 2020-01-27 14:09 UTC
Labels: needs/more-info, topic/documentation
