### ISSUE TITLE
gem repo server is responding with a 403 error [install]

### ISSUE THREAD

**Issue by daniel-sciome** [sparklemotion/nokogiri#2417] opened 2022-01-09 14:52 UTC
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.0-x64-unknown.gemspec.rz)
```

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

```
the output of "nokogiri -v" goes here
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
the mkmf.log file contents go here
```

**Tell us about your system!**

What is the output from `ruby -v`? ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

What is the output from `gem -v`? 2.7.6

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/svobodadl/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.5
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/svobodadl/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.5.0
     - /home/svobodadl/.gem/ruby/2.5.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin

```

If you're using Bundler:
- what is the output from `bundle version`?
- what is the output from `bundle config`? (Take care to redact any credentials)

```
the output of "bundle config" goes here
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`

If Linux or a BSD variant, please note:
- the distro you're using ubuntu 18.04.6
- the output of `uname -a` Linux [hostname] 4.15.0-166-generic #174-Ubuntu SMP Wed Dec 8 19:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- the contents of `/etc/lsb-release`.
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
If Windows, please note:
- whether you're installing the precompiled gems, or compiling yourself with DevKit precompiled
- the version of RubyInstaller you've installed
- or if you're not using RubyInstaller, how did you install Ruby? apt

**Comment by flavorjones** [comment] 2022-01-09 16:21
Duplicate of https://github.com/sparklemotion/nokogiri/issues/2415

> So, the first thing you should take note of is that Nokogiri v1.13.0 does not support Ruby 2.5, which is probably a case that your version of rubygems or bundler doesn't support.
> 
> I would recommend using a modern version of Bundler to resolve your dependencies if you can, because Bundler is smart enough to use the latest version of a gem that supports your version of Ruby.
> 
> If that doesn't solve your problem, or you can't use Bundler, then please try upgrading rubygems.
> 
> If _that_ doesn't solve your problem, please open a bug report upstream with rubygems. Unfortunately there's nothing we can do as Nokogiri gem maintainers to change this behavior!
>

**Closed by flavorjones** 2022-01-09 16:21 UTC
Labels: topic/installation

**Comment by daniel-sciome** [comment] 2022-01-09 22:04
this worked not 10 days ago.

**Comment by flavorjones** [comment] 2022-01-10 19:55
You said:

> What is the output from ruby -v? ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

I said:

> So, the first thing you should take note of is that Nokogiri v1.13.0 does not support Ruby 2.5

Please help me understand if I've missed something.
