### ISSUE TITLE
HTML::DocumentFragment - invalid encoding on windows&jruby

### ISSUE THREAD

**Issue by ahorek** [sparklemotion/nokogiri#1216] opened 2014-12-30 17:40 UTC
See https://github.com/jruby/jruby/issues/2089

**Comment by jughead** [comment] 2015-03-16 09:59
@ahorek, don't you forget to add encoding comment at the top of your script?

**Comment by flavorjones** [comment] 2023-01-22 04:15
Can't reproduce. Closing.

**Closed by flavorjones** 2023-01-22 04:15 UTC
