### ISSUE TITLE
Having trouble0

### ISSUE THREAD

**Issue by jaishanker123** [sparklemotion/nokogiri#1631] opened 2017-04-24 13:32 UTC
## If you're having trouble installing 

Dear, I am facing installation issue on Windows 7, 32 bit OS.

Please help and find output error below.

Nokogiri ...D:\branch_new\gems>gem install nokogiri-1.6.8.gem
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri-1.6.8.gem:
        ERROR: Failed to build gem native extension.

    D:/ruby/ruby/bin/ruby.exe extconf.rb
Using pkg-config version 1.1.9
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of zlib-1.2.8.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install
************************************************************************

Downloading zlib-1.2.8.tar.gz (100%)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/ruby/ruby/bin/ruby
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:259:in `verify_file': Downloaded file 'D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.8/ports/archives/zlib-1.2.8
.tar.gz' has wrong hash: expected: 44d667c142d7cda120332623eab69f40 is: 231f7ee33bfdc938b664efd0e1625e06 (RuntimeError)
        from D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:51:in `block in download'
        from D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:49:in `each'
        from D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:49:in `download'
        from D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:146:in `cook'
        from extconf.rb:364:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:363:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:482:in `<main>'

Gem files will remain installed in D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.8 for inspection.
Results logged to D:/ruby/ruby/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.8/ext/nokogiri/gem_make.out

D:\branch_new\gems>

**Comment by flavorjones** [comment] 2017-04-24 13:43
duplicate of #1632

**Closed by flavorjones** 2017-04-24 13:43 UTC
